import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_name': 'مركز الأذكار',
      'app_tagline': 'رفيقك الروحي اليومي',
      'nav_home': 'الرئيسية',
      'nav_adhkar': 'مركز الأذكار',
      'nav_quran': 'المصحف الشريف',
      'nav_zakat': 'الزكاة',
      'nav_prayer': 'مواقيت الصلاة',
      'nav_tasbih': 'التسبيح',
      'nav_tracker': 'مسار الالتزام',
      'nav_settings': 'الإعدادات',
      'nav_hadith': 'الأحاديث والأحكام',
      'nav_favorites': 'المفضلة',
      'nav_search': 'البحث',
      
      'common_loading': 'جاري التحميل...',
      'common_error': 'حدث خطأ ما',
      'common_retry': 'إعادة المحاولة',
      'common_close': 'إغلاق',
      'common_save': 'حفظ',
      'common_cancel': 'إلغاء',
      'common_done': 'تم',
      'common_back': 'رجوع',
      'common_more': 'المزيد...',
      'common_copied': 'تم النسخ!',

      'home_greeting_morning': 'صباح الخير',
      'home_greeting_evening': 'مساء الخير',
      'home_greeting_night': 'ليلة مباركة',
      'home_salawat_banner': 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
      'home_salawat_subtitle': 'اضغط للصلاة على النبي ﷺ',
      'home_salawat_today': 'صلوات اليوم',
      'home_hadith_of_hour': 'حديث الساعة',
      'home_verse_of_hour': 'آية الساعة',
      'home_daily_inspiration': 'إلهام اليوم',
      'home_morning_desc': 'حصن المسلم وبركة الصباح',
      'home_evening_desc': 'طمأنينة المساء وحماية الذكر',
      'home_morning_ruqyah_desc': 'حصن المسلم مع الرقية الشرعية للوقاية والتحصين',
      'home_evening_ruqyah_desc': 'طمأنينة المساء مع الرقية الشرعية للحفظ والشفاء',
      'home_sleep_desc': 'سنن النبي ﷺ قبل النوم',
      'home_prayer_desc': 'الأذكار المشروعة بعد السلام',

      'zakat_title': 'حاسبة الزكاة',
      'zakat_subtitle': 'احسب زكاتك بدقة وسهولة بناءً على أسعار الذهب والفضة اليومية',
      'zakat_assets_input': 'الأصول والمدخرات',
      'zakat_cash': 'النقود والسيولة',
      'zakat_trade': 'عروض التجارة',
      'zakat_gold_weight': 'وزن الذهب عيار 24 (بالجرام)',
      'zakat_silver_weight': 'وزن الفضة (بالجرام)',
      'zakat_debts': 'الديون والالتزامات',
      'zakat_nisab_info': 'معلومة عن النصاب:',
      'zakat_nisab_desc': 'يُحسب النصاب بناءً على قيمة 85 جرام من الذهب عيار 24. إذا بلغت أموالك هذا القدر وحال عليها الحول، وجبت فيها الزكاة بنسبة 2.5%.',
      'zakat_result_title': 'ملخص الزكاة',
      'zakat_total_wealth': 'إجمالي ثروتك',
      'zakat_amount_due': 'الزكاة المستحقة',
      'zakat_eligible': 'تجب عليك الزكاة',
      'zakat_not_eligible': 'لم تبلغ أموالك النصاب',
      'zakat_market_prices': 'أسعار السوق الحالية',
      'zakat_gold_price': 'سعر الذهب (عيار 24)',
      'zakat_silver_price': 'سعر الفضة',

      'prayer_today_prayers': 'صلوات اليوم',
      'prayer_calendar': 'التقويم',
      'prayer_fajr': 'الفجر',
      'prayer_sunrise': 'الشروق',
      'prayer_dhuhr': 'الظهر',
      'prayer_asr': 'العصر',
      'prayer_maghrib': 'المغرب',
      'prayer_isha': 'العشاء',
      'prayer_next': 'الصلاة القادمة',
      'prayer_remaining': 'المتبقي',
      'prayer_qibla_direction': 'اتجاه القبلة',
      'prayer_qibla_degree': 'درجة القبلة',
      'prayer_qibla_from_north': 'من الشمال',
      'prayer_qibla_subtitle': 'بوصلة دقيقة لاتجاه القبلة',
      'prayer_qibla_guide': 'إرشادات الاستخدام',
      'prayer_qibla_hint': 'ضع الهاتف في سطح أفقي مستوٍ. قم بتدوير الهاتف حتى يتطابق السهم مع الكعبة المشرفة.',

      'tasbih_title': 'المسبحة الإلكترونية',
      'tasbih_count': 'العدد الحالي',
      'tasbih_target': 'الهدف',
      'tasbih_set_target': 'تحديد الهدف',
      'tasbih_reset': 'إعادة ضبط',
      'tasbih_vibrate': 'الاهتزاز',
      'tasbih_sound': 'الصوت',
      'tasbih_custom': 'مخصص',

      'settings_title': 'الإعدادات',
      'settings_language': 'اللغة',
      'settings_theme': 'المظهر',
      'settings_dark': 'داكن',
      'settings_light': 'فاتح',
      'settings_theme_fajr': 'الفجر (خزامي روحاني)',
      'settings_theme_duha': 'الضحى (سماوي صباحي)',
      'settings_theme_maghrib': 'المغرب (غروب شاحب)',
      'settings_theme_sahar': 'السحر (سمائي ليلي)',
      'settings_font_size': 'حجم الخط',
      'settings_font_sm': 'صغير',
      'settings_font_md': 'متوسط',
      'settings_font_lg': 'كبير',
      'settings_font_xl': 'كبير جداً',

      'favorites_subtitle': 'قائمة الأذكار والأحكام المحفوظة لديك',
      'favorites_empty': 'لا توجد مفضلات بعد',
      'favorites_empty_desc': 'قم بإضافة الأذكار أو الأحكام لتظهر هنا',
    },
    'en': {
      'app_name': 'Islamic Hub',
      'app_tagline': 'Your Daily Spiritual Companion',
      'nav_home': 'Home',
      'nav_adhkar': 'Adhkar Hub',
      'nav_quran': 'Quran',
      'nav_zakat': 'Zakat',
      'nav_prayer': 'Prayer Times',
      'nav_tasbih': 'Tasbih',
      'nav_tracker': 'Worship Tracker',
      'nav_settings': 'Settings',
      'nav_hadith': 'Hadith',
      'nav_favorites': 'Favorites',
      'nav_search': 'Search',

      'common_loading': 'Loading...',
      'common_error': 'An error occurred',
      'common_retry': 'Retry',
      'common_close': 'Close',
      'common_save': 'Save',
      'common_cancel': 'Cancel',
      'common_done': 'Done',
      'common_back': 'Back',
      'common_more': 'More...',
      'common_copied': 'Copied!',

      'home_greeting_morning': 'Good Morning',
      'home_greeting_evening': 'Good Evening',
      'home_greeting_night': 'Blessed Night',
      'home_salawat_banner': 'O Allah, send prayers and peace upon our Prophet Muhammad',
      'home_salawat_subtitle': 'Tap to pray upon the Prophet ﷺ',
      'home_salawat_today': 'Prayers Today',
      'home_hadith_of_hour': 'Hadith of the Hour',
      'home_verse_of_hour': 'Verse of the Hour',
      'home_daily_inspiration': 'Daily Inspiration',
      'home_morning_desc': 'Fortress of the Muslim & Morning Blessing',
      'home_evening_desc': 'Evening Tranquility & Remembrance Protection',
      'home_morning_ruqyah_desc': 'Morning Adhkar merged with Ruqyah Shariah for protection',
      'home_evening_ruqyah_desc': 'Evening Adhkar merged with Ruqyah Shariah for healing',
      'home_sleep_desc': 'Sunnah of the Prophet ﷺ before sleeping',
      'home_prayer_desc': 'Prescribed remembrances after peace',

      'zakat_title': 'Zakat Calculator',
      'zakat_subtitle': 'Calculate your Zakat accurately based on daily gold and silver rates',
      'zakat_assets_input': 'Assets & Savings',
      'zakat_cash': 'Cash & Liquidity',
      'zakat_trade': 'Business Assets',
      'zakat_gold_weight': 'Gold Weight (grams - 24K)',
      'zakat_silver_weight': 'Silver Weight (grams)',
      'zakat_debts': 'Debts & Obligations',
      'zakat_nisab_info': 'Nisab Information:',
      'zakat_nisab_desc': 'Nisab is calculated based on the value of 85 grams of 24K gold. If your wealth reaches this amount and a full lunar year passes, 2.5% Zakat is due.',
      'zakat_result_title': 'Zakat Summary',
      'zakat_total_wealth': 'Total Wealth',
      'zakat_amount_due': 'Zakat Due',
      'zakat_eligible': 'Zakat is Obligatory',
      'zakat_not_eligible': 'Wealth has not reached Nisab',
      'zakat_market_prices': 'Current Market Prices',
      'zakat_gold_price': 'Gold Price (24K)',
      'zakat_silver_price': 'Silver Price',

      'prayer_today_prayers': 'Today\'s Prayers',
      'prayer_calendar': 'Calendar',
      'prayer_fajr': 'Fajr',
      'prayer_sunrise': 'Sunrise',
      'prayer_dhuhr': 'Dhuhr',
      'prayer_asr': 'Asr',
      'prayer_maghrib': 'Maghrib',
      'prayer_isha': 'Isha',
      'prayer_next': 'Next Prayer',
      'prayer_remaining': 'Remaining',
      'prayer_qibla_direction': 'Qibla Direction',
      'prayer_qibla_degree': 'Qibla Degree',
      'prayer_qibla_from_north': 'from North',
      'prayer_qibla_subtitle': 'Accurate Qibla compass direction',
      'prayer_qibla_guide': 'Usage Guide',
      'prayer_qibla_hint': 'Place the phone on a flat horizontal surface. Rotate the phone until the arrow aligns with the Kaaba.',

      'tasbih_title': 'Electronic Tasbih',
      'tasbih_count': 'Current Count',
      'tasbih_target': 'Target',
      'tasbih_set_target': 'Set Target',
      'tasbih_reset': 'Reset',
      'tasbih_vibrate': 'Vibration',
      'tasbih_sound': 'Sound',
      'tasbih_custom': 'Custom',

      'settings_title': 'Settings',
      'settings_language': 'Language',
      'settings_theme': 'Theme',
      'settings_dark': 'Dark',
      'settings_light': 'Light',
      'settings_theme_fajr': 'Fajr (Lavender Spiritual)',
      'settings_theme_duha': 'Duha (Sky Blue Morning)',
      'settings_theme_maghrib': 'Maghrib (Sunset Pale)',
      'settings_theme_sahar': 'Sahar (Night Celestial)',
      'settings_font_size': 'Font Size',
      'settings_font_sm': 'Small',
      'settings_font_md': 'Medium',
      'settings_font_lg': 'Large',
      'settings_font_xl': 'Extra Large',

      'favorites_subtitle': 'List of saved adhkar and rulings',
      'favorites_empty': 'No favorites yet',
      'favorites_empty_desc': 'Add adhkar or rulings to see them here',
    },
    'am': {
      'app_name': 'ኢስላሚክ ሀብ',
      'app_tagline': 'ዕለታዊ መንፈሳዊ አጋርዎ',
      'nav_home': 'መነሻ',
      'nav_adhkar': 'አዝካር',
      'nav_quran': 'ቁርኣን',
      'nav_zakat': 'ዘካት',
      'nav_prayer': 'የሶላት ሰዓታት',
      'nav_tasbih': 'ተስቢሕ',
      'nav_tracker': 'ግስጋሴ',
      'nav_settings': 'ቅንብሮች',
      'nav_hadith': 'ሐዲስ',
      'nav_favorites': 'ተወዳጆች',
      'nav_search': 'ፈልግ',

      'common_loading': 'በመጫን ላይ...',
      'common_error': 'ስህተት ተከስቷል',
      'common_retry': 'ድገም',
      'common_close': 'ዝጋ',
      'common_save': 'አስቀምጥ',
      'common_cancel': 'ሰርዝ',
      'common_done': 'ተጠናቋል',
      'common_back': 'ተመለስ',
      'common_more': 'ተጨማሪ...',
      'common_copied': 'ተቀድቷል!',

      'home_greeting_morning': 'መልካም ጠዋት',
      'home_greeting_evening': 'መልካም ምሽት',
      'home_greeting_night': 'መልካም ሌሊት',
      'home_salawat_banner': 'አላህም ፀሎትና ሰላም በነቢያችን ሙሐመድ ላይ ይላክ',
      'home_salawat_subtitle': 'በነቢዩ ላይ ፀሎት ለማድረግ ይጫኑ',
      'home_salawat_today': 'የዛሬ ፀሎት',
      'home_hadith_of_hour': 'የሰዓቱ ሐዲስ',
      'home_verse_of_hour': 'የሰዓቱ አንቀጽ',
      'home_daily_inspiration': 'ዕለታዊ አነሳሽ',
      'home_morning_desc': 'የጠዋት ጥበቃና በረከት',
      'home_evening_desc': 'የምሽት ሰላምና ጥበቃ',
      'home_morning_ruqyah_desc': 'የጠዋት አዝካር ከሩቅያህ ጋር ለጥበቃ የተዋሃደ',
      'home_evening_ruqyah_desc': 'የምሽት አዝካር ከሩቅያህ ጋር ለፈውስ የተዋሃደ',
      'home_sleep_desc': 'የነቢዩ ሱና ከእንቅልፍ በፊት',
      'home_prayer_desc': 'ከግዴታ ሶላት በኋላ አዝካር',

      'zakat_title': 'የዘካት ማውጫ',
      'zakat_subtitle': 'በዕለታዊ ወርቅና ብር ዋጋ መሰረት ዘካትዎን በትክክል ያስሉ',
      'zakat_assets_input': 'ንብረትና ቁጠባ',
      'zakat_cash': 'ጥሬ ገንዘብ',
      'zakat_trade': 'የንግድ ንብረት',
      'zakat_gold_weight': 'የወርቅ ክብደት (ግራም - 24ኬ)',
      'zakat_silver_weight': 'የብር ክብደት (ግራም)',
      'zakat_debts': 'ዕዳዎች',
      'zakat_nisab_info': 'ስለ ኒሳብ:',
      'zakat_nisab_desc': 'ኒሳብ በ85ግ 24ኬ ወርቅ ዋጋ ይሰላል። ግምት ሲደርስና ሙሉ ጨረቃ ዓመት ሲያልፍ ዘካት 2.5% ይሆናል።',
      'zakat_result_title': 'የዘካት ማጠቃለያ',
      'zakat_total_wealth': 'ጠቅላላ ንብረት',
      'zakat_amount_due': 'የዘካት መጠን',
      'zakat_eligible': 'ዘካት ግዴታ ነው',
      'zakat_not_eligible': 'ኒሳብ አልደረሰም',
      'zakat_market_prices': 'የአሁኑ የገبهያ ዋጋዎች',
      'zakat_gold_price': 'የወርቅ ዋጋ (24ኬ)',
      'zakat_silver_price': 'የብር ዋጋ',

      'prayer_today_prayers': 'የዛሬ ሶላቶች',
      'prayer_calendar': 'ቀን መቁጠሪያ',
      'prayer_fajr': 'ፈጅር',
      'prayer_sunrise': 'ፀሐይ መውጫ',
      'prayer_dhuhr': 'ዙሁር',
      'prayer_asr': 'ዐሥር',
      'prayer_maghrib': 'መግሪብ',
      'prayer_isha': 'ዒሻ',
      'prayer_next': 'ቀጣይ ሶላት',
      'prayer_remaining': 'ቀሪ ጊዜ',
      'prayer_qibla_direction': 'የቂብላ አቅጣጫ',
      'prayer_qibla_degree': 'ዲግሪ',
      'prayer_qibla_from_north': 'ከሰሜን',
      'prayer_qibla_subtitle': 'የቂብላ አቅጣጫ ጠቋሚ',
      'prayer_qibla_guide': 'የአጠቃቀም መመሪያ',
      'prayer_qibla_hint': 'ስልኩን ጠፍጣፋ መሬት ላይ ያድርጉት። ቀስቱ ከካዕባ ጋር እስኪስተካከል ድረስ ስልኩን ያሽከርክሩት።',

      'tasbih_title': 'ኤሌክትሮኒክ ተስቢሕ',
      'tasbih_count': 'የአሁን ቁጥር',
      'tasbih_target': 'ግብ',
      'tasbih_set_target': 'ግብ ያዘጋጁ',
      'tasbih_reset': 'ዳግም ጀምር',
      'tasbih_vibrate': 'ንዝረት',
      'tasbih_sound': 'ድምፅ',
      'tasbih_custom': 'ብጁ',

      'settings_title': 'ቅንብሮች',
      'settings_language': 'ቋንቋ',
      'settings_theme': 'ገጽታ',
      'settings_dark': 'ጨለማ',
      'settings_light': 'ብርሃን',
      'settings_theme_fajr': 'ፈጅር (የድምቀት)',
      'settings_theme_duha': 'ዱሐ (ብርሃን)',
      'settings_theme_maghrib': 'መግሪብ (ሰላም)',
      'settings_theme_sahar': 'ሰሐር (መንፈስ)',
      'settings_font_size': 'የፊደል መጠን',
      'settings_font_sm': 'ትንሽ',
      'settings_font_md': 'መካከለኛ',
      'settings_font_lg': 'ትልቅ',
      'settings_font_xl': 'በጣም ትልቅ',

      'favorites_subtitle': 'የተቀመጡት አዝካር ዝርዝር',
      'favorites_empty': 'እስካሁን ተወዳጆች የሉም',
      'favorites_empty_desc': 'አዝካር ሲያስቀምጡ እዚህ ይታያሉ',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['ar']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en', 'am'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
