export default {
  app: { name: "Islamski Zikrovi", tagline: "Trajna Sadaka" },
  nav: { home: "Početna", morning: "Jutarnji Zikrovi", evening: "Večernji Zikrovi", both: "Jutro i Večer", sleep: "Zikrovi za Spavanje", prayer: "Zikrovi Namaza", ruqyah: "Rukja", times: "Vremena Namaza", fasting: "Dani Posta", tasbih: "Tesbih" },
  home: { greeting_morning: "Dobro jutro", greeting_evening: "Dobro veče", greeting_night: "Laku noć", today: "Danas", progress: "Napredak danas", completed: "završeno", start: "Počni" },
  prayer: { fajr: "Sabah", sunrise: "Izlazak sunca", dhuhr: "Podne", asr: "Ikindija", maghrib: "Akšam", isha: "Jacija", next: "Sljedeći Namaz", remaining: "Preostalo vrijeme", location: "Vaša lokacija", location_required: "Molimo dozvolite pristup lokaciji", allow_location: "Dozvoli", enter_city: "Unesite grad", calculation_method: "Metoda izračuna", methods: { MuslimWorldLeague: "Islamska Svjetska Liga", Egyptian: "Egipatski organ", Karachi: "Univerzitet Karachi", UmmAlQura: "Umm Al-Kura", Dubai: "Dubai", NorthAmerica: "Sjeverna Amerika", Kuwait: "Kuvajt", Qatar: "Katar", Singapore: "Singapur", Turkey: "Turska" }, last_third: "Posljednja trećina noći", imsak: "Imsak" },
  dhikr: { count: "Broj", times: "puta", source: "Izvor", tap_to_count: "Tapnite za brojanje", completed_msg: "Bravo! Zikrovi završeni", reset: "Resetuj", reset_all: "Resetuj sve", morning_form: "Jutarnji oblik", evening_form: "Večernji oblik", note: "Napomena", benefit: "Vrlina" },
  tasbih: { title: "Slobodni Tesbih", count: "Trenutni broj", target: "Cilj", set_target: "Postavi cilj", reset: "Resetuj", vibrate: "Vibracija", sound: "Zvuk", custom: "Prilagođeno", saved: "Sačuvano" },
  fasting: { title: "Sunnetski Dani Posta", white_days: "Bijeli Dani", white_days_desc: "13., 14. i 15. svakog hidžretskog mjeseca", white_days_hadith: "Post tri dana svakog mjeseca je kao post cijelog života", arafah: "Dan Arefata", arafah_desc: "9. Zul-hidždže", arafah_hadith: "Post na Arefatu briše grijehe prošle i naredne godine", dhul_hijjah: "Prvih deset dana Zul-hidždže", dhul_hijjah_desc: "Od 1. do 9. Zul-hidždže", dhul_hijjah_hadith: "Nema boljih dana za dobra djela", ashura: "Dan Ašure", ashura_desc: "10. Muharrem", ashura_hadith: "Post na Ašuri briše grijehe prošle godine", tasua: "Dan Tasu'a", tasua_desc: "9. Muharrem", tasua_hadith: "Ako doživim iduću godinu, postit ću i 9.", monday: "Ponedjeljak", monday_desc: "Svaki ponedjeljak u sedmici", monday_hadith: "To je dan mog rođenja i objave", thursday: "Četvrtak", thursday_desc: "Svaki četvrtak u sedmici", thursday_hadith: "Djela se prikazuju ponedjeljkom i četvrtkom", shawwal: "Šest dana Ševvala", shawwal_desc: "Šest dana Ševvala nakon Bajrama", shawwal_hadith: "Ko posti Ramazan pa mu doda šest dana Ševvala, kao da je postio cijeli život", shaban: "Ša'ban", shaban_desc: "Većinu mjeseca Ša'bana", shaban_hadith: "To je mjesec od kojeg su ljudi nemarni", upcoming: "Predstojeće", today_fasting: "Danas", passed: "Prošlo", gregorian_date: "Gregorijanski datum", hijri_date: "Hidžretski datum", days_remaining: "{{days}} dana preostalo", days_passed: "Prije {{days}} dana", monthly: "Mjesečno", weekly: "Sedmično", yearly: "Godišnje" },
  dates: { hijri: "h.g.", gregorian: "n.e.", days: ["Nedjelja", "Ponedjeljak", "Utorak", "Srijeda", "Četvrtak", "Petak", "Subota"] },
  settings: { title: "Postavke", language: "Jezik", theme: "Tema", dark: "Tamno", light: "Svjetlo", system: "Sistem", calculation: "Metoda izračuna", font_size: "Veličina fonta", notifications: "Obavijesti" },
  common: { loading: "Učitavanje...", error: "Došlo je do greške", retry: "Pokušaj ponovo", close: "Zatvori", save: "Sačuvaj", cancel: "Otkaži", done: "Gotovo", search: "Pretraži", share: "Podijeli", copied: "Kopirano", copy: "Kopiraj", of: "od", back: "Nazad" },
};
