export default {
  app: { name: "Islamische Adhkar", tagline: "Anhaltende Wohltätigkeit" },
  nav: { home: "Startseite", morning: "Morgendhikr", evening: "Abenddhikr", both: "Morgen & Abend", sleep: "Schlafdhikr", prayer: "Gebetsdhikr", ruqyah: "Ruqyah", times: "Gebetszeiten", fasting: "Fastentage", tasbih: "Tasbih" },
  home: { greeting_morning: "Guten Morgen", greeting_evening: "Guten Abend", greeting_night: "Gute Nacht", today: "Heute", progress: "Heutiger Fortschritt", completed: "abgeschlossen", start: "Beginnen" },
  prayer: { fajr: "Fadschr", sunrise: "Sonnenaufgang", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Ischa", next: "Nächstes Gebet", remaining: "Verbleibende Zeit", location: "Ihr Standort", location_required: "Bitte erlauben Sie den Standortzugriff", allow_location: "Erlauben", enter_city: "Stadt eingeben", calculation_method: "Berechnungsmethode", methods: { MuslimWorldLeague: "Muslimische Weltliga", Egyptian: "Ägyptische Behörde", Karachi: "Universität Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "Nordamerika", Kuwait: "Kuwait", Qatar: "Katar", Singapore: "Singapur", Turkey: "Türkei" }, last_third: "Letztes Nachtdrittel", imsak: "Imsak" },
  dhikr: { count: "Anzahl", times: "Mal", source: "Quelle", tap_to_count: "Tippen zum Zählen", completed_msg: "Gut gemacht! Adhkar abgeschlossen", reset: "Zurücksetzen", reset_all: "Alles zurücksetzen", morning_form: "Morgenform", evening_form: "Abendform", note: "Hinweis", benefit: "Tugend" },
  tasbih: { title: "Freies Tasbih", count: "Aktueller Zähler", target: "Ziel", set_target: "Ziel setzen", reset: "Zurücksetzen", vibrate: "Vibrieren", sound: "Ton", custom: "Benutzerdefiniert", saved: "Gespeichert" },
  fasting: { title: "Sunna-Fastentage", white_days: "Die weißen Tage", white_days_desc: "13., 14. und 15. jedes Hijri-Monats", white_days_hadith: "Drei Tage jeden Monat fasten ist wie ein ganzes Leben fasten", arafah: "Tag von Arafah", arafah_desc: "9. Dhul Hiddscha", arafah_hadith: "Fasten an Arafah sühnt Sünden des vergangenen und kommenden Jahres", dhul_hijjah: "Erste zehn des Dhul Hiddscha", dhul_hijjah_desc: "Vom 1. bis 9. Dhul Hiddscha", dhul_hijjah_hadith: "Kein Tag ist besser für gute Taten", ashura: "Tag Aschura", ashura_desc: "10. Muharram", ashura_hadith: "Fasten an Aschura sühnt Sünden des vergangenen Jahres", tasua: "Tag Tasua", tasua_desc: "9. Muharram", tasua_hadith: "Wenn ich nächstes Jahr lebe, werde ich auch den 9. fasten", monday: "Montag", monday_desc: "Jeden Montag der Woche", monday_hadith: "Das ist der Tag meiner Geburt und der Offenbarung", thursday: "Donnerstag", thursday_desc: "Jeden Donnerstag der Woche", thursday_hadith: "Taten werden montags und donnerstags präsentiert", shawwal: "Sechs Tage Schawwal", shawwal_desc: "Sechs Tage Schawwal nach dem Fest", shawwal_hadith: "Wer Ramadan fastet und dann sechs von Schawwal, ist wie ewig fastend", shaban: "Scha'ban", shaban_desc: "Den größten Teil des Monats Scha'ban", shaban_hadith: "Es ist ein Monat, dem die Menschen gleichgültig gegenüberstehen", upcoming: "Bevorstehend", today_fasting: "Heute", passed: "Vergangen", gregorian_date: "Gregorianisches Datum", hijri_date: "Hijri-Datum", days_remaining: "{{days}} Tage verbleibend", days_passed: "Vor {{days}} Tagen", monthly: "Monatlich", weekly: "Wöchentlich", yearly: "Jährlich" },
  dates: { hijri: "n. H.", gregorian: "n. Chr.", days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] },
  settings: { title: "Einstellungen", language: "Sprache", theme: "Design", dark: "Dunkel", light: "Hell", system: "System", calculation: "Gebetsberechnungsmethode", font_size: "Schriftgröße", notifications: "Benachrichtigungen" },
  common: { loading: "Laden...", error: "Ein Fehler ist aufgetreten", retry: "Erneut versuchen", close: "Schließen", save: "Speichern", cancel: "Abbrechen", done: "Fertig", search: "Suchen", share: "Teilen", copied: "Kopiert", copy: "Kopieren", of: "von", back: "Zurück" },
};
