export default {
  app: { name: "Adhkar Islámicos", tagline: "Caridad Continua" },
  nav: { home: "Inicio", morning: "Adhkar Mañana", evening: "Adhkar Tarde", both: "Mañana y Tarde", sleep: "Adhkar Sueño", prayer: "Adhkar Oración", ruqyah: "Ruqyah", times: "Horarios de Oración", fasting: "Días de Ayuno", tasbih: "Tasbih" },
  home: { greeting_morning: "Buenos días", greeting_evening: "Buenas tardes", greeting_night: "Buenas noches", today: "Hoy", progress: "Progreso de hoy", completed: "completado", start: "Comenzar" },
  prayer: { fajr: "Fajr", sunrise: "Amanecer", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Próxima Oración", remaining: "Tiempo restante", location: "Tu ubicación", location_required: "Por favor, permite el acceso a tu ubicación", allow_location: "Permitir", enter_city: "Ingresa ciudad", calculation_method: "Método de cálculo", methods: { MuslimWorldLeague: "Liga Mundial Islámica", Egyptian: "Autoridad Egipcia", Karachi: "Universidad de Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubái", NorthAmerica: "Norteamérica", Kuwait: "Kuwait", Qatar: "Catar", Singapore: "Singapur", Turkey: "Turquía" }, last_third: "Último tercio de la noche", imsak: "Imsak" },
  dhikr: { count: "Cuenta", times: "veces", source: "Fuente", tap_to_count: "Toca para contar", completed_msg: "¡Bien hecho! Adhkar completados", reset: "Restablecer", reset_all: "Restablecer todo", morning_form: "Forma matutina", evening_form: "Forma vespertina", note: "Nota", benefit: "Virtud" },
  tasbih: { title: "Tasbih Libre", count: "Cuenta actual", target: "Meta", set_target: "Establecer meta", reset: "Restablecer", vibrate: "Vibrar", sound: "Sonido", custom: "Personalizado", saved: "Guardado" },
  fasting: { title: "Días de Ayuno Sunna", white_days: "Los Días Blancos", white_days_desc: "13, 14 y 15 de cada mes hijri", white_days_hadith: "Ayunar tres días de cada mes es como ayunar toda la vida", arafah: "Día de Arafah", arafah_desc: "9 de Dhul Hijjah", arafah_hadith: "El ayuno de Arafah expía los pecados del año pasado y del venidero", dhul_hijjah: "Los primeros diez de Dhul Hijjah", dhul_hijjah_desc: "Del 1 al 9 de Dhul Hijjah", dhul_hijjah_hadith: "No hay días mejores para las buenas obras", ashura: "Día de Ashura", ashura_desc: "10 de Muharram", ashura_hadith: "El ayuno de Ashura expía los pecados del año pasado", tasua: "Día de Tasua", tasua_desc: "9 de Muharram", tasua_hadith: "Si vivo el próximo año, ayunaré también el 9", monday: "Lunes", monday_desc: "Cada lunes de la semana", monday_hadith: "Ese es el día de mi nacimiento y de la revelación", thursday: "Jueves", thursday_desc: "Cada jueves de la semana", thursday_hadith: "Las obras se presentan los lunes y jueves", shawwal: "Seis días de Shawwal", shawwal_desc: "Seis días de Shawwal después del Eid", shawwal_hadith: "Quien ayuna Ramadán y luego seis de Shawwal es como ayunar eternamente", shaban: "Sha'ban", shaban_desc: "La mayor parte del mes de Sha'ban", shaban_hadith: "Es un mes del que la gente es descuidada", upcoming: "Próximo", today_fasting: "Hoy", passed: "Pasado", gregorian_date: "Fecha gregoriana", hijri_date: "Fecha hijri", days_remaining: "{{days}} días restantes", days_passed: "Hace {{days}} días", monthly: "Mensual", weekly: "Semanal", yearly: "Anual" },
  dates: { hijri: "H", gregorian: "d.C.", days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"] },
  settings: { title: "Configuración", language: "Idioma", theme: "Tema", dark: "Oscuro", light: "Claro", system: "Sistema", calculation: "Método de cálculo", font_size: "Tamaño de fuente", notifications: "Notificaciones" },
  common: { loading: "Cargando...", error: "Ocurrió un error", retry: "Reintentar", close: "Cerrar", save: "Guardar", cancel: "Cancelar", done: "Listo", search: "Buscar", share: "Compartir", copied: "Copiado", copy: "Copiar", of: "de", back: "Atrás" },
};
