export default {
  app: { name: "اذکار اسلامی", tagline: "صدقه جاریه" },
  nav: { home: "خانه", morning: "اذکار صبح", evening: "اذکار شب", both: "صبح و شب", sleep: "اذکار خواب", prayer: "اذکار نماز", ruqyah: "رقیه شرعیه", times: "اوقات نماز", fasting: "روزهای روزه", tasbih: "تسبیح" },
  home: { greeting_morning: "صبح بخیر", greeting_evening: "عصر بخیر", greeting_night: "شب بخیر", today: "امروز", progress: "پیشرفت امروز", completed: "تکمیل شد", start: "شروع" },
  prayer: { fajr: "فجر", sunrise: "طلوع آفتاب", dhuhr: "ظهر", asr: "عصر", maghrib: "مغرب", isha: "عشاء", next: "نماز بعدی", remaining: "زمان باقی‌مانده", location: "موقعیت شما", location_required: "لطفاً دسترسی به موقعیت را مجاز کنید", allow_location: "مجاز کردن", enter_city: "شهر را وارد کنید", calculation_method: "روش محاسبه", methods: { MuslimWorldLeague: "رابطة العالم الاسلامی", Egyptian: "مرجع مصری", Karachi: "دانشگاه کراچی", UmmAlQura: "ام‌القری", Dubai: "دبی", NorthAmerica: "آمریکای شمالی", Kuwait: "کویت", Qatar: "قطر", Singapore: "سنگاپور", Turkey: "ترکیه" }, last_third: "یک سوم آخر شب", imsak: "امساک" },
  dhikr: { count: "تعداد", times: "بار", source: "منبع", tap_to_count: "برای شمارش لمس کنید", completed_msg: "آفرین! اذکار تکمیل شد", reset: "بازنشانی", reset_all: "بازنشانی همه", morning_form: "فرم صبح", evening_form: "فرم شب", note: "یادداشت", benefit: "فضیلت" },
  tasbih: { title: "تسبیح آزاد", count: "شمارش فعلی", target: "هدف", set_target: "تنظیم هدف", reset: "بازنشانی", vibrate: "لرزش", sound: "صدا", custom: "سفارشی", saved: "ذخیره شد" },
  fasting: { title: "روزهای روزه مستحبی", white_days: "ایام البیض", white_days_desc: "۱۳، ۱۴ و ۱۵ هر ماه هجری", white_days_hadith: "روزه سه روز در هر ماه مانند روزه تمام عمر است", arafah: "روز عرفه", arafah_desc: "نهم ذی‌الحجه", arafah_hadith: "روزه روز عرفه کفاره گناهان سال گذشته و آینده است", dhul_hijjah: "ده روز اول ذی‌الحجه", dhul_hijjah_desc: "از اول تا نهم ذی‌الحجه", dhul_hijjah_hadith: "هیچ روزی برای اعمال صالح بهتر از این ده روز نیست", ashura: "روز عاشورا", ashura_desc: "دهم محرم", ashura_hadith: "روزه عاشورا کفاره گناهان سال گذشته است", tasua: "روز تاسوعا", tasua_desc: "نهم محرم", tasua_hadith: "اگر سال آینده زنده بمانم، نهم را هم روزه می‌گیرم", monday: "دوشنبه", monday_desc: "هر دوشنبه هفته", monday_hadith: "آن روزی است که در آن متولد شدم و وحی نازل شد", thursday: "پنج‌شنبه", thursday_desc: "هر پنج‌شنبه هفته", thursday_hadith: "اعمال روز دوشنبه و پنج‌شنبه ارائه می‌شود", shawwal: "شش روز شوال", shawwal_desc: "شش روز شوال پس از عید", shawwal_hadith: "کسی که رمضان را روزه بگیرد سپس شش روز شوال، مانند کسی است که تمام عمر روزه گرفته", shaban: "شعبان", shaban_desc: "بیشتر ماه شعبان", shaban_hadith: "این ماهی است که مردم از آن غافل هستند", upcoming: "آینده", today_fasting: "امروز", passed: "گذشته", gregorian_date: "تاریخ میلادی", hijri_date: "تاریخ هجری", days_remaining: "{{days}} روز مانده", days_passed: "{{days}} روز پیش", monthly: "ماهانه", weekly: "هفتگی", yearly: "سالانه" },
  dates: { hijri: "ه.ق", gregorian: "م", days: ["یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنج‌شنبه", "جمعه", "شنبه"] },
  settings: { title: "تنظیمات", language: "زبان", theme: "قالب", dark: "تیره", light: "روشن", system: "سیستم", calculation: "روش محاسبه", font_size: "اندازه فونت", notifications: "اعلان‌ها" },
  common: { loading: "در حال بارگذاری...", error: "خطایی رخ داد", retry: "تلاش مجدد", close: "بستن", save: "ذخیره", cancel: "انصراف", done: "تمام", search: "جستجو", share: "اشتراک‌گذاری", copied: "کپی شد", copy: "کپی", of: "از", back: "بازگشت" },
};
