export default {
  app: { name: "Adhkar Islamiques", tagline: "Sadaqa Jariya" },
  nav: { home: "Accueil", morning: "Adhkar du Matin", evening: "Adhkar du Soir", both: "Matin & Soir", sleep: "Adhkar du Sommeil", prayer: "Adhkar de la Prière", ruqyah: "Ruqyah", times: "Horaires de Prière", fasting: "Jours de Jeûne", tasbih: "Tasbih" },
  home: { greeting_morning: "Bonjour", greeting_evening: "Bonsoir", greeting_night: "Bonne nuit", today: "Aujourd'hui", progress: "Progrès du jour", completed: "complété", start: "Commencer" },
  prayer: { fajr: "Fajr", sunrise: "Lever", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Prochaine Prière", remaining: "Temps restant", location: "Votre position", location_required: "Autorisez l'accès à votre position", allow_location: "Autoriser", enter_city: "Entrez la ville", calculation_method: "Méthode de calcul", methods: { MuslimWorldLeague: "Ligue Islamique Mondiale", Egyptian: "Autorité Égyptienne", Karachi: "Université de Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubaï", NorthAmerica: "Amérique du Nord", Kuwait: "Koweït", Qatar: "Qatar", Singapore: "Singapour", Turkey: "Turquie" }, last_third: "Dernier tiers de nuit", imsak: "Imsak" },
  dhikr: { count: "Compte", times: "fois", source: "Source", tap_to_count: "Appuyez pour compter", completed_msg: "Bravo! Adhkar terminés", reset: "Réinitialiser", reset_all: "Tout réinitialiser", morning_form: "Forme du matin", evening_form: "Forme du soir", note: "Note", benefit: "Vertu" },
  tasbih: { title: "Tasbih Libre", count: "Compte actuel", target: "Objectif", set_target: "Définir objectif", reset: "Réinitialiser", vibrate: "Vibrer", sound: "Son", custom: "Personnalisé", saved: "Sauvegardé" },
  fasting: { title: "Jours de Jeûne Sunna", white_days: "Les Jours Blancs", white_days_desc: "13, 14 et 15 de chaque mois hégirien", white_days_hadith: "Jeûner trois jours chaque mois équivaut à jeûner toute une vie", arafah: "Jour d'Arafah", arafah_desc: "9 Dhul Hijjah", arafah_hadith: "Jeûner Arafah expie les péchés de l'année passée et à venir", dhul_hijjah: "Dix premiers de Dhul Hijjah", dhul_hijjah_desc: "Du 1er au 9 Dhul Hijjah", dhul_hijjah_hadith: "Aucun jour n'est meilleur pour les bonnes actions", ashura: "Jour d'Achoura", ashura_desc: "10 Mouharram", ashura_hadith: "Jeûner Achoura expie les péchés de l'année passée", tasua: "Jour de Tachoua", tasua_desc: "9 Mouharram", tasua_hadith: "Si je vis l'année prochaine, je jeûnerai le 9 aussi", monday: "Lundi", monday_desc: "Chaque lundi de la semaine", monday_hadith: "C'est le jour de ma naissance et de la révélation", thursday: "Jeudi", thursday_desc: "Chaque jeudi de la semaine", thursday_hadith: "Les actes sont présentés les lundis et jeudis", shawwal: "Six jours de Chawwal", shawwal_desc: "Six jours de Chawwal après l'Aïd", shawwal_hadith: "Qui jeûne Ramadan puis six de Chawwal est comme jeûner pour toujours", shaban: "Chaâban", shaban_desc: "La plupart du mois de Chaâban", shaban_hadith: "C'est un mois dont les gens sont négligents", upcoming: "À venir", today_fasting: "Aujourd'hui", passed: "Passé", gregorian_date: "Date grégorienne", hijri_date: "Date hégirienne", days_remaining: "{{days}} jours restants", days_passed: "Il y a {{days}} jours", monthly: "Mensuel", weekly: "Hebdomadaire", yearly: "Annuel" },
  dates: { hijri: "H", gregorian: "ap. J.-C.", days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"] },
  settings: { title: "Paramètres", language: "Langue", theme: "Thème", dark: "Sombre", light: "Clair", system: "Système", calculation: "Méthode de calcul", font_size: "Taille de police", notifications: "Notifications" },
  common: { loading: "Chargement...", error: "Une erreur s'est produite", retry: "Réessayer", close: "Fermer", save: "Sauvegarder", cancel: "Annuler", done: "Terminé", search: "Rechercher", share: "Partager", copied: "Copié", copy: "Copier", of: "sur", back: "Retour" },
};
