export default {
  app: { name: "इस्लामी अज़कार", tagline: "सदक़ा-ए-जारिया" },
  nav: { home: "होम", morning: "सुबह के अज़कार", evening: "शाम के अज़कार", both: "सुबह और शाम", sleep: "सोने के अज़कार", prayer: "नमाज़ के अज़कार", ruqyah: "रुक़्या", times: "नमाज़ के वक़्त", fasting: "रोज़े के दिन", tasbih: "तस्बीह" },
  home: { greeting_morning: "सुप्रभात", greeting_evening: "शुभ संध्या", greeting_night: "शुभ रात्रि", today: "आज", progress: "आज की प्रगति", completed: "पूर्ण", start: "शुरू करें" },
  prayer: { fajr: "फ़ज्र", sunrise: "सूर्योदय", dhuhr: "ज़ुहर", asr: "अस्र", maghrib: "मग़रिब", isha: "इशा", next: "अगली नमाज़", remaining: "बचा हुआ समय", location: "आपका स्थान", location_required: "कृपया अपने स्थान तक पहुंच की अनुमति दें", allow_location: "अनुमति दें", enter_city: "शहर दर्ज करें", calculation_method: "गणना विधि", methods: { MuslimWorldLeague: "मुस्लिम वर्ल्ड लीग", Egyptian: "मिस्र प्राधिकरण", Karachi: "कराची विश्वविद्यालय", UmmAlQura: "उम्मुल-क़ुरा", Dubai: "दुबई", NorthAmerica: "उत्तरी अमेरिका", Kuwait: "कुवैत", Qatar: "क़तर", Singapore: "सिंगापुर", Turkey: "तुर्की" }, last_third: "रात का आखिरी तिहाई", imsak: "इम्साक" },
  dhikr: { count: "संख्या", times: "बार", source: "स्रोत", tap_to_count: "गिनने के लिए टैप करें", completed_msg: "शाबाश! अज़कार पूर्ण हुए", reset: "रीसेट", reset_all: "सब रीसेट", morning_form: "सुबह का रूप", evening_form: "शाम का रूप", note: "नोट", benefit: "फ़ज़ीलत" },
  tasbih: { title: "मुक्त तस्बीह", count: "वर्तमान गिनती", target: "लक्ष्य", set_target: "लक्ष्य निर्धारित करें", reset: "रीसेट", vibrate: "कंपन", sound: "ध्वनि", custom: "कस्टम", saved: "सहेजा गया" },
  fasting: { title: "सुन्नत रोज़े के दिन", white_days: "सफ़ेद दिन", white_days_desc: "हर हिजरी महीने की 13, 14 और 15 तारीख", white_days_hadith: "हर महीने तीन दिन रोज़ा रखना पूरे जीवन रोज़ा रखने जैसा है", arafah: "अरफ़ा का दिन", arafah_desc: "ज़िलहिज्जा की 9 तारीख", arafah_hadith: "अरफ़ा का रोज़ा पिछले और अगले साल के गुनाहों को माफ़ करता है", dhul_hijjah: "ज़िलहिज्जा के पहले दस दिन", dhul_hijjah_desc: "ज़िलहिज्जा की 1 से 9 तारीख", dhul_hijjah_hadith: "इन दस दिनों से बेहतर नेक काम के लिए कोई दिन नहीं", ashura: "आशूरा का दिन", ashura_desc: "मुहर्रम की 10 तारीख", ashura_hadith: "आशूरा का रोज़ा पिछले साल के गुनाहों को माफ़ करता है", tasua: "तासूआ का दिन", tasua_desc: "मुहर्रम की 9 तारीख", tasua_hadith: "अगर मैं अगले साल जीवित रहा तो 9 को भी रोज़ा रखूंगा", monday: "सोमवार", monday_desc: "हर हफ़्ते सोमवार", monday_hadith: "यह मेरे जन्म और वही नाज़िल होने का दिन है", thursday: "गुरुवार", thursday_desc: "हर हफ़्ते गुरुवार", thursday_hadith: "सोमवार और गुरुवार को अमल पेश किए जाते हैं", shawwal: "शव्वाल के छह रोज़े", shawwal_desc: "ईद के बाद शव्वाल के छह दिन", shawwal_hadith: "जो रमज़ान के रोज़े रखे फिर शव्वाल के छह, वो जैसे हमेशा रोज़े रखे", shaban: "शाबान", shaban_desc: "शाबान के महीने का अधिकांश", shaban_hadith: "यह वह महीना है जिसे लोग नजरअंदाज़ करते हैं", upcoming: "आने वाला", today_fasting: "आज", passed: "बीत गया", gregorian_date: "ईसवी तारीख", hijri_date: "हिजरी तारीख", days_remaining: "{{days}} दिन बाकी", days_passed: "{{days}} दिन पहले", monthly: "मासिक", weekly: "साप्ताहिक", yearly: "वार्षिक" },
  dates: { hijri: "हि.", gregorian: "ई.", days: ["रविवार", "सोमवार", "मंगलवार", "बुधवार", "गुरुवार", "शुक्रवार", "शनिवार"] },
  settings: { title: "सेटिंग्स", language: "भाषा", theme: "थीम", dark: "गहरा", light: "हल्का", system: "सिस्टम", calculation: "गणना विधि", font_size: "फ़ॉन्ट आकार", notifications: "सूचनाएं" },
  common: { loading: "लोड हो रहा है...", error: "एक त्रुटि हुई", retry: "पुनः प्रयास करें", close: "बंद करें", save: "सहेजें", cancel: "रद्द करें", done: "हो गया", search: "खोज", share: "साझा करें", copied: "कॉपी हुआ", copy: "कॉपी करें", of: "का", back: "वापस" },
};
