export default {
  app: { name: "Dzikir Islam", tagline: "Amal Jariyah" },
  nav: { home: "Beranda", morning: "Dzikir Pagi", evening: "Dzikir Sore", both: "Pagi & Sore", sleep: "Dzikir Tidur", prayer: "Dzikir Sholat", ruqyah: "Ruqyah", times: "Waktu Sholat", fasting: "Hari Puasa", tasbih: "Tasbih" },
  home: { greeting_morning: "Selamat Pagi", greeting_evening: "Selamat Sore", greeting_night: "Selamat Malam", today: "Hari Ini", progress: "Kemajuan Hari Ini", completed: "selesai", start: "Mulai" },
  prayer: { fajr: "Subuh", sunrise: "Terbit", dhuhr: "Dzuhur", asr: "Ashar", maghrib: "Maghrib", isha: "Isya", next: "Sholat Berikutnya", remaining: "Sisa Waktu", location: "Lokasi Anda", location_required: "Mohon izinkan akses lokasi Anda", allow_location: "Izinkan", enter_city: "Masukkan kota", calculation_method: "Metode Perhitungan", methods: { MuslimWorldLeague: "Liga Muslim Dunia", Egyptian: "Otoritas Mesir", Karachi: "Universitas Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "Amerika Utara", Kuwait: "Kuwait", Qatar: "Qatar", Singapore: "Singapura", Turkey: "Turki" }, last_third: "Sepertiga Malam Terakhir", imsak: "Imsak" },
  dhikr: { count: "Jumlah", times: "kali", source: "Sumber", tap_to_count: "Ketuk untuk menghitung", completed_msg: "Bagus! Dzikir selesai", reset: "Reset", reset_all: "Reset Semua", morning_form: "Bentuk Pagi", evening_form: "Bentuk Sore", note: "Catatan", benefit: "Keutamaan" },
  tasbih: { title: "Tasbih Bebas", count: "Hitungan Saat Ini", target: "Target", set_target: "Atur Target", reset: "Reset", vibrate: "Getar", sound: "Suara", custom: "Kustom", saved: "Tersimpan" },
  fasting: { title: "Hari Puasa Sunnah", white_days: "Hari-Hari Putih", white_days_desc: "13, 14 dan 15 setiap bulan Hijriyah", white_days_hadith: "Puasa tiga hari setiap bulan seperti puasa seumur hidup", arafah: "Hari Arafah", arafah_desc: "9 Dzulhijjah", arafah_hadith: "Puasa Arafah menghapus dosa tahun lalu dan tahun mendatang", dhul_hijjah: "Sepuluh Pertama Dzulhijjah", dhul_hijjah_desc: "Dari 1 hingga 9 Dzulhijjah", dhul_hijjah_hadith: "Tidak ada hari yang lebih baik untuk amal sholeh", ashura: "Hari Asyura", ashura_desc: "10 Muharram", ashura_hadith: "Puasa Asyura menghapus dosa tahun lalu", tasua: "Hari Tasua", tasua_desc: "9 Muharram", tasua_hadith: "Jika aku hidup tahun depan, aku akan puasa hari ke-9 juga", monday: "Senin", monday_desc: "Setiap Senin dalam seminggu", monday_hadith: "Itu adalah hari kelahiranku dan turunnya wahyu", thursday: "Kamis", thursday_desc: "Setiap Kamis dalam seminggu", thursday_hadith: "Amal dipersembahkan pada hari Senin dan Kamis", shawwal: "Enam Hari Syawal", shawwal_desc: "Enam hari Syawal setelah Idul Fitri", shawwal_hadith: "Siapa yang puasa Ramadhan lalu enam hari Syawal seolah puasa selamanya", shaban: "Sya'ban", shaban_desc: "Sebagian besar bulan Sya'ban", shaban_hadith: "Ini adalah bulan yang dilalaikan orang-orang", upcoming: "Mendatang", today_fasting: "Hari Ini", passed: "Sudah Lewat", gregorian_date: "Tanggal Masehi", hijri_date: "Tanggal Hijriyah", days_remaining: "{{days}} hari lagi", days_passed: "{{days}} hari yang lalu", monthly: "Bulanan", weekly: "Mingguan", yearly: "Tahunan" },
  dates: { hijri: "H", gregorian: "M", days: ["Ahad", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"] },
  settings: { title: "Pengaturan", language: "Bahasa", theme: "Tema", dark: "Gelap", light: "Terang", system: "Sistem", calculation: "Metode Perhitungan", font_size: "Ukuran Font", notifications: "Notifikasi" },
  common: { loading: "Memuat...", error: "Terjadi kesalahan", retry: "Coba lagi", close: "Tutup", save: "Simpan", cancel: "Batal", done: "Selesai", search: "Cari", share: "Bagikan", copied: "Disalin", copy: "Salin", of: "dari", back: "Kembali" },
};
