export default {
  app: { name: "Adhkar Islamici", tagline: "Sadaqa Continua" },
  nav: { home: "Home", morning: "Adhkar Mattina", evening: "Adhkar Sera", both: "Mattina e Sera", sleep: "Adhkar Sonno", prayer: "Adhkar Preghiera", ruqyah: "Ruqyah", times: "Orari Preghiera", fasting: "Giorni di Digiuno", tasbih: "Tasbih" },
  home: { greeting_morning: "Buongiorno", greeting_evening: "Buona sera", greeting_night: "Buona notte", today: "Oggi", progress: "Progresso di Oggi", completed: "completato", start: "Inizia" },
  prayer: { fajr: "Fajr", sunrise: "Alba", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Prossima Preghiera", remaining: "Tempo rimanente", location: "La tua posizione", location_required: "Consenti l'accesso alla tua posizione", allow_location: "Consenti", enter_city: "Inserisci città", calculation_method: "Metodo di calcolo", methods: { MuslimWorldLeague: "Lega Islamica Mondiale", Egyptian: "Autorità Egiziana", Karachi: "Università di Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "Nord America", Kuwait: "Kuwait", Qatar: "Qatar", Singapore: "Singapore", Turkey: "Turchia" }, last_third: "Ultimo terzo della notte", imsak: "Imsak" },
  dhikr: { count: "Conteggio", times: "volte", source: "Fonte", tap_to_count: "Tocca per contare", completed_msg: "Bravo! Adhkar completati", reset: "Ripristina", reset_all: "Ripristina tutto", morning_form: "Forma mattutina", evening_form: "Forma serale", note: "Nota", benefit: "Virtù" },
  tasbih: { title: "Tasbih Libero", count: "Conteggio attuale", target: "Obiettivo", set_target: "Imposta obiettivo", reset: "Ripristina", vibrate: "Vibra", sound: "Suono", custom: "Personalizzato", saved: "Salvato" },
  fasting: { title: "Giorni di Digiuno Sunnah", white_days: "I Giorni Bianchi", white_days_desc: "13, 14 e 15 di ogni mese Hijri", white_days_hadith: "Digiunare tre giorni ogni mese è come digiunare per tutta la vita", arafah: "Giorno di Arafah", arafah_desc: "9 Dhul Hijjah", arafah_hadith: "Il digiuno di Arafah espia i peccati dell'anno passato e futuro", dhul_hijjah: "Primi dieci di Dhul Hijjah", dhul_hijjah_desc: "Dal 1 al 9 Dhul Hijjah", dhul_hijjah_hadith: "Non ci sono giorni migliori per le buone azioni", ashura: "Giorno di Ashura", ashura_desc: "10 Muharram", ashura_hadith: "Il digiuno di Ashura espia i peccati dell'anno passato", tasua: "Giorno di Tasua", tasua_desc: "9 Muharram", tasua_hadith: "Se sopravvivo all'anno prossimo, digiunerò anche il 9", monday: "Lunedì", monday_desc: "Ogni lunedì della settimana", monday_hadith: "È il giorno della mia nascita e della rivelazione", thursday: "Giovedì", thursday_desc: "Ogni giovedì della settimana", thursday_hadith: "Le azioni vengono presentate il lunedì e giovedì", shawwal: "Sei giorni di Shawwal", shawwal_desc: "Sei giorni di Shawwal dopo l'Eid", shawwal_hadith: "Chi digiuna il Ramadan poi sei di Shawwal è come se digiunasse per sempre", shaban: "Sha'ban", shaban_desc: "La maggior parte del mese di Sha'ban", shaban_hadith: "È un mese di cui le persone sono negligenti", upcoming: "Prossimo", today_fasting: "Oggi", passed: "Passato", gregorian_date: "Data gregoriana", hijri_date: "Data Hijri", days_remaining: "{{days}} giorni rimanenti", days_passed: "{{days}} giorni fa", monthly: "Mensile", weekly: "Settimanale", yearly: "Annuale" },
  dates: { hijri: "H", gregorian: "d.C.", days: ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"] },
  settings: { title: "Impostazioni", language: "Lingua", theme: "Tema", dark: "Scuro", light: "Chiaro", system: "Sistema", calculation: "Metodo di calcolo", font_size: "Dimensione del carattere", notifications: "Notifiche" },
  common: { loading: "Caricamento...", error: "Si è verificato un errore", retry: "Riprova", close: "Chiudi", save: "Salva", cancel: "Annulla", done: "Fatto", search: "Cerca", share: "Condividi", copied: "Copiato", copy: "Copia", of: "di", back: "Indietro" },
};
