export default {
  app: { name: "Adhkar Islâmicos", tagline: "Sadaqa Contínua" },
  nav: { home: "Início", morning: "Adhkar Manhã", evening: "Adhkar Tarde", both: "Manhã e Tarde", sleep: "Adhkar Sono", prayer: "Adhkar Oração", ruqyah: "Ruqyah", times: "Horários de Oração", fasting: "Dias de Jejum", tasbih: "Tasbih" },
  home: { greeting_morning: "Bom dia", greeting_evening: "Boa tarde", greeting_night: "Boa noite", today: "Hoje", progress: "Progresso de Hoje", completed: "concluído", start: "Começar" },
  prayer: { fajr: "Fajr", sunrise: "Nascer do sol", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Próxima Oração", remaining: "Tempo restante", location: "Sua localização", location_required: "Por favor, permita o acesso à sua localização", allow_location: "Permitir", enter_city: "Digite a cidade", calculation_method: "Método de cálculo", methods: { MuslimWorldLeague: "Liga Mundial Islâmica", Egyptian: "Autoridade Egípcia", Karachi: "Universidade de Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "América do Norte", Kuwait: "Kuwait", Qatar: "Catar", Singapore: "Singapura", Turkey: "Turquia" }, last_third: "Último terço da noite", imsak: "Imsak" },
  dhikr: { count: "Contagem", times: "vezes", source: "Fonte", tap_to_count: "Toque para contar", completed_msg: "Parabéns! Adhkar concluídos", reset: "Reiniciar", reset_all: "Reiniciar tudo", morning_form: "Forma matinal", evening_form: "Forma vespertina", note: "Nota", benefit: "Virtude" },
  tasbih: { title: "Tasbih Livre", count: "Contagem atual", target: "Meta", set_target: "Definir meta", reset: "Reiniciar", vibrate: "Vibrar", sound: "Som", custom: "Personalizado", saved: "Salvo" },
  fasting: { title: "Dias de Jejum Sunnah", white_days: "Os Dias Brancos", white_days_desc: "13, 14 e 15 de cada mês Hijri", white_days_hadith: "Jejuar três dias por mês é como jejuar a vida toda", arafah: "Dia de Arafah", arafah_desc: "9 de Dhul Hijjah", arafah_hadith: "O jejum de Arafah expía pecados do ano passado e futuro", dhul_hijjah: "Primeiros dez de Dhul Hijjah", dhul_hijjah_desc: "Do 1 ao 9 de Dhul Hijjah", dhul_hijjah_hadith: "Não há dias melhores para boas ações", ashura: "Dia de Ashura", ashura_desc: "10 de Muharram", ashura_hadith: "O jejum de Ashura expía pecados do ano passado", tasua: "Dia de Tasua", tasua_desc: "9 de Muharram", tasua_hadith: "Se eu viver até o próximo ano, jejuarei também o 9", monday: "Segunda-feira", monday_desc: "Toda segunda-feira da semana", monday_hadith: "Esse é o dia do meu nascimento e da revelação", thursday: "Quinta-feira", thursday_desc: "Toda quinta-feira da semana", thursday_hadith: "Os atos são apresentados nas segundas e quintas", shawwal: "Seis dias de Shawwal", shawwal_desc: "Seis dias de Shawwal após o Eid", shawwal_hadith: "Quem jejua o Ramadã e depois seis de Shawwal é como jeju para sempre", shaban: "Sha'ban", shaban_desc: "A maior parte do mês de Sha'ban", shaban_hadith: "É um mês do qual as pessoas são descuidadas", upcoming: "Próximo", today_fasting: "Hoje", passed: "Passou", gregorian_date: "Data gregoriana", hijri_date: "Data Hijri", days_remaining: "{{days}} dias restantes", days_passed: "Há {{days}} dias", monthly: "Mensal", weekly: "Semanal", yearly: "Anual" },
  dates: { hijri: "H", gregorian: "d.C.", days: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"] },
  settings: { title: "Configurações", language: "Idioma", theme: "Tema", dark: "Escuro", light: "Claro", system: "Sistema", calculation: "Método de cálculo", font_size: "Tamanho da fonte", notifications: "Notificações" },
  common: { loading: "Carregando...", error: "Ocorreu um erro", retry: "Tentar novamente", close: "Fechar", save: "Salvar", cancel: "Cancelar", done: "Concluído", search: "Pesquisar", share: "Compartilhar", copied: "Copiado", copy: "Copiar", of: "de", back: "Voltar" },
};
