export default {
  app: { name: "Islamiska Adhkar", tagline: "Fortlöpande Välgörenhet" },
  nav: { home: "Hem", morning: "Morgon Adhkar", evening: "Kväll Adhkar", both: "Morgon & Kväll", sleep: "Sömn Adhkar", prayer: "Bön Adhkar", ruqyah: "Ruqyah", times: "Bönetider", fasting: "Fastadagar", tasbih: "Tasbih" },
  home: { greeting_morning: "God morgon", greeting_evening: "God kväll", greeting_night: "God natt", today: "Idag", progress: "Dagens framsteg", completed: "slutfört", start: "Börja" },
  prayer: { fajr: "Fajr", sunrise: "Soluppgång", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Nästa Bön", remaining: "Återstående tid", location: "Din plats", location_required: "Tillåt åtkomst till din plats", allow_location: "Tillåt", enter_city: "Ange stad", calculation_method: "Beräkningsmetod", methods: { MuslimWorldLeague: "Islamiska Världsförbundet", Egyptian: "Egyptisk myndighet", Karachi: "Karachis universitet", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "Nordamerika", Kuwait: "Kuwait", Qatar: "Qatar", Singapore: "Singapore", Turkey: "Turkiet" }, last_third: "Nattens sista tredjedel", imsak: "Imsak" },
  dhikr: { count: "Antal", times: "gånger", source: "Källa", tap_to_count: "Tryck för att räkna", completed_msg: "Bra gjort! Adhkar klara", reset: "Återställ", reset_all: "Återställ allt", morning_form: "Morgonform", evening_form: "Kvällsform", note: "Notera", benefit: "Dygd" },
  tasbih: { title: "Fri Tasbih", count: "Aktuellt antal", target: "Mål", set_target: "Sätt mål", reset: "Återställ", vibrate: "Vibrera", sound: "Ljud", custom: "Anpassad", saved: "Sparad" },
  fasting: { title: "Sunnah Fastadagar", white_days: "De vita dagarna", white_days_desc: "13, 14 och 15 i varje Hijri-månad", white_days_hadith: "Att fasta tre dagar varje månad är som att fasta hela livet", arafah: "Arafah-dagen", arafah_desc: "9 Dhul Hijjah", arafah_hadith: "Fasta på Arafah sonar synder det senaste och kommande året", dhul_hijjah: "Första tio i Dhul Hijjah", dhul_hijjah_desc: "Från 1 till 9 Dhul Hijjah", dhul_hijjah_hadith: "Inga dagar är bättre för goda gärningar", ashura: "Ashura-dagen", ashura_desc: "10 Muharram", ashura_hadith: "Fasta på Ashura sonar synder det senaste året", tasua: "Tasua-dagen", tasua_desc: "9 Muharram", tasua_hadith: "Om jag lever nästa år ska jag fasta den 9:e också", monday: "Måndag", monday_desc: "Varje måndag i veckan", monday_hadith: "Det är dagen jag föddes och uppenbarelsen kom", thursday: "Torsdag", thursday_desc: "Varje torsdag i veckan", thursday_hadith: "Gärningar presenteras på måndag och torsdag", shawwal: "Sex dagar av Shawwal", shawwal_desc: "Sex dagar Shawwal efter Eid", shawwal_hadith: "Den som fastar Ramadan och sedan sex av Shawwal är som att fasta evigt", shaban: "Sha'ban", shaban_desc: "Större delen av månaden Sha'ban", shaban_hadith: "Det är en månad som folk försummar", upcoming: "Kommande", today_fasting: "Idag", passed: "Passerat", gregorian_date: "Gregorianskt datum", hijri_date: "Hijri-datum", days_remaining: "{{days}} dagar kvar", days_passed: "{{days}} dagar sedan", monthly: "Månadsvis", weekly: "Veckovis", yearly: "Årsvis" },
  dates: { hijri: "H", gregorian: "e.Kr.", days: ["Söndag", "Måndag", "Tisdag", "Onsdag", "Torsdag", "Fredag", "Lördag"] },
  settings: { title: "Inställningar", language: "Språk", theme: "Tema", dark: "Mörkt", light: "Ljust", system: "System", calculation: "Beräkningsmetod", font_size: "Textstorlek", notifications: "Aviseringar" },
  common: { loading: "Laddar...", error: "Ett fel uppstod", retry: "Försök igen", close: "Stäng", save: "Spara", cancel: "Avbryt", done: "Klar", search: "Sök", share: "Dela", copied: "Kopierat", copy: "Kopiera", of: "av", back: "Tillbaka" },
};
