export default {
  app: { name: "Adhkar za Kiislamu", tagline: "Sadaka ya Kudumu" },
  nav: { home: "Nyumbani", morning: "Adhkar za Asubuhi", evening: "Adhkar za Jioni", both: "Asubuhi na Jioni", sleep: "Adhkar za Kulala", prayer: "Adhkar za Swala", ruqyah: "Ruqyah", times: "Nyakati za Swala", fasting: "Siku za Saumu", tasbih: "Tasbih" },
  home: { greeting_morning: "Habari za asubuhi", greeting_evening: "Habari za jioni", greeting_night: "Usiku mwema", today: "Leo", progress: "Maendeleo ya Leo", completed: "imekamilika", start: "Anza" },
  prayer: { fajr: "Alfajiri", sunrise: "Mapambazuko", dhuhr: "Adhuhuri", asr: "Alasiri", maghrib: "Magharibi", isha: "Isha", next: "Swala Inayofuata", remaining: "Muda Uliobaki", location: "Mahali Pako", location_required: "Tafadhali ruhusu ufikiaji wa mahali pako", allow_location: "Ruhusu", enter_city: "Ingiza mji", calculation_method: "Njia ya Kuhesabu", methods: { MuslimWorldLeague: "Liga ya Ulimwengu wa Kiislamu", Egyptian: "Mamlaka ya Misri", Karachi: "Chuo Kikuu cha Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "Amerika Kaskazini", Kuwait: "Kuwait", Qatar: "Qatar", Singapore: "Singapore", Turkey: "Uturuki" }, last_third: "Theluthi ya Mwisho ya Usiku", imsak: "Imsak" },
  dhikr: { count: "Hesabu", times: "mara", source: "Chanzo", tap_to_count: "Gonga kuhesabu", completed_msg: "Hongera! Adhkar zimekamilika", reset: "Weka upya", reset_all: "Weka upya zote", morning_form: "Mfumo wa Asubuhi", evening_form: "Mfumo wa Jioni", note: "Kumbuka", benefit: "Fadhila" },
  tasbih: { title: "Tasbih Huru", count: "Hesabu ya Sasa", target: "Lengo", set_target: "Weka Lengo", reset: "Weka upya", vibrate: "Tetemeka", sound: "Sauti", custom: "Maalum", saved: "Imehifadhiwa" },
  fasting: { title: "Siku za Saumu ya Sunnah", white_days: "Siku Nyeupe", white_days_desc: "13, 14 na 15 ya kila mwezi wa Hijri", white_days_hadith: "Kufunga siku tatu kila mwezi ni kama kufunga maisha yote", arafah: "Siku ya Arafah", arafah_desc: "9 Dhul Hijjah", arafah_hadith: "Saumu ya Arafah inafuta dhambi za mwaka uliopita na unaokuja", dhul_hijjah: "Kumi za Kwanza za Dhul Hijjah", dhul_hijjah_desc: "Kutoka 1 hadi 9 Dhul Hijjah", dhul_hijjah_hadith: "Hakuna siku bora zaidi kwa matendo mema", ashura: "Siku ya Ashura", ashura_desc: "10 Muharram", ashura_hadith: "Saumu ya Ashura inafuta dhambi za mwaka uliopita", tasua: "Siku ya Tasua", tasua_desc: "9 Muharram", tasua_hadith: "Nikibaki hadi mwaka ujao, nitafunga siku ya 9 pia", monday: "Jumatatu", monday_desc: "Kila Jumatatu ya wiki", monday_hadith: "Hiyo ni siku niliyozaliwa na Wahyi ulipoteremshwa", thursday: "Alhamisi", thursday_desc: "Kila Alhamisi ya wiki", thursday_hadith: "Matendo yanawasilishwa siku za Jumatatu na Alhamisi", shawwal: "Siku Sita za Shawwal", shawwal_desc: "Siku sita za Shawwal baada ya Eid", shawwal_hadith: "Anayefunga Ramadhani kisha sita za Shawwal ni kama amefunga daima", shaban: "Sha'ban", shaban_desc: "Sehemu kubwa ya mwezi wa Sha'ban", shaban_hadith: "Ni mwezi ambao watu hawajali", upcoming: "Inayokuja", today_fasting: "Leo", passed: "Imepita", gregorian_date: "Tarehe ya Kigiriki", hijri_date: "Tarehe ya Hijri", days_remaining: "Siku {{days}} zimebaki", days_passed: "Siku {{days}} zilizopita", monthly: "Kila Mwezi", weekly: "Kila Wiki", yearly: "Kila Mwaka" },
  dates: { hijri: "H", gregorian: "BK", days: ["Jumapili", "Jumatatu", "Jumanne", "Jumatano", "Alhamisi", "Ijumaa", "Jumamosi"] },
  settings: { title: "Mipangilio", language: "Lugha", theme: "Mandhari", dark: "Giza", light: "Mwanga", system: "Mfumo", calculation: "Njia ya Kuhesabu", font_size: "Ukubwa wa Herufi", notifications: "Arifa" },
  common: { loading: "Inapakia...", error: "Hitilafu imetokea", retry: "Jaribu tena", close: "Funga", save: "Hifadhi", cancel: "Ghairi", done: "Imekamilika", search: "Tafuta", share: "Shiriki", copied: "Imenakiliwa", copy: "Nakili", of: "ya", back: "Rudi" },
};
