// Template for new locale files — copy this and translate all keys
export default {
  app: { name: "Islamic Hub", tagline: "Your Daily Spiritual Companion" },
  nav: { home: "Home", adhkar: "Adhkar", morning: "Morning Adhkar", evening: "Evening Adhkar", both: "Morning & Evening", sleep: "Sleep Adhkar", prayer: "After Prayer", ruqyah: "Ruqyah", times: "Prayer Times", fasting: "Fasting Days", tasbih: "Tasbih", settings: "Settings", hadith: "Hadith & Rulings", quran: "Quran", qibla: "Qibla", zakat: "Zakat", favorites: "Favorites", search: "Search" },
  home: { greeting_morning: "Good morning", greeting_evening: "Good evening", greeting_night: "Good night", today: "Today", progress: "Today's progress", completed: "completed", start: "Start" },
  prayer: { fajr: "Fajr", sunrise: "Sunrise", dhuhr: "Dhuhr", asr: "Asr", maghrib: "Maghrib", isha: "Isha", next: "Next Prayer", remaining: "Time remaining", location: "Your location", location_required: "Allow location access", allow_location: "Allow", enter_city: "Enter city", calculation_method: "Calculation method", methods: { MuslimWorldLeague: "Muslim World League", Egyptian: "Egyptian Authority", Karachi: "University of Karachi", UmmAlQura: "Umm Al-Qura", Dubai: "Dubai", NorthAmerica: "North America", Kuwait: "Kuwait", Qatar: "Qatar", Singapore: "Singapore", Turkey: "Turkey" }, last_third: "Last third of the night", imsak: "Imsak" },
  dhikr: { count: "Count", times: "times", source: "Source", tap_to_count: "Tap to count", completed_msg: "Completed!", reset: "Reset", reset_all: "Reset all", morning_form: "Morning form", evening_form: "Evening form", note: "Note", benefit: "Benefit" },
  tasbih: { title: "Free Tasbih", count: "Current count", target: "Target", set_target: "Set target", reset: "Reset", vibrate: "Vibrate", sound: "Sound", custom: "Custom", saved: "Saved" },
  fasting: { title: "Sunnah Fasting Days", white_days: "White Days", white_days_desc: "13th, 14th, 15th of each Hijri month", white_days_hadith: "Fasting 3 days each month is like fasting forever", arafah: "Day of Arafah", arafah_desc: "9 Dhul Hijjah", arafah_hadith: "Fasting Arafah expiates sins of the previous and coming year", monday: "Monday", monday_desc: "Every Monday", monday_hadith: "The day I was born and revelation came down", thursday: "Thursday", thursday_desc: "Every Thursday", thursday_hadith: "Deeds are presented on Monday and Thursday", shawwal: "6 Days of Shawwal", shawwal_desc: "6 days after Eid", shawwal_hadith: "Whoever fasts Ramadan and 6 of Shawwal is like fasting forever", upcoming: "Upcoming", today_fasting: "Today", passed: "Passed", gregorian_date: "Gregorian", hijri_date: "Hijri", days_remaining: "{{days}} days remaining", days_passed: "{{days}} days ago", monthly: "Monthly", weekly: "Weekly", yearly: "Yearly" },
  dates: { hijri: "H", gregorian: "AD", days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] },
  settings: { title: "Settings", language: "Language", theme: "Theme", dark: "Dark", light: "Light", system: "System", calculation: "Calculation method", font_size: "Font size", notifications: "Notifications" },
  common: { loading: "Loading...", error: "An error occurred", retry: "Retry", close: "Close", save: "Save", cancel: "Cancel", done: "Done", search: "Search", share: "Share", copied: "Copied", copy: "Copy", of: "of", back: "Back" },
  hadith: { title: "Hadith & Rulings", subtitle: "Encyclopedia of Hadiths, Rulings, and Scientific Views", search_placeholder: "Search for a hadith, ruling, or keyword...", loading_data: "Loading data...", no_results: "No results found", try_another_search: "Try another keyword", cat_all: "All", cat_tafsir: "Tafsir", cat_creed: "Creed", cat_fiqh: "Fiqh", cat_hadith: "Hadith", cat_ethics: "Ethics", cat_general: "General" },
};
