// This file is auto-generated by the migration script
export interface AdhkarAudioConfig {
  type: "quran" | "dureihim";
  surah?: number;
  ayahs?: number[];
  filename?: string;
}

export const adhkarAudioMap: Record<string, AdhkarAudioConfig> = {
  "quran_dua_sidq": {
    "type": "quran",
    "surah": 17,
    "ayahs": [
      80
    ]
  },
  "quran_dua_ilman": {
    "type": "quran",
    "surah": 20,
    "ayahs": [
      114
    ]
  },
  "quran_dua_rabbana_taqabbal": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      127,
      128
    ]
  },
  "quran_dua_shifa": {
    "type": "quran",
    "surah": 21,
    "ayahs": [
      83
    ]
  },
  "quran_dua_hukman": {
    "type": "quran",
    "surah": 26,
    "ayahs": [
      83,
      84,
      85
    ]
  },
  "quran_dua_tawakul": {
    "type": "quran",
    "surah": 10,
    "ayahs": [
      85,
      86
    ]
  },
  "quran_dua_maghfirah": {
    "type": "quran",
    "surah": 3,
    "ayahs": [
      147
    ]
  },
  "quran_dua_rahmah_parents": {
    "type": "quran",
    "surah": 17,
    "ayahs": [
      24
    ]
  },
  "quran_dua_yusuf_tawafa": {
    "type": "quran",
    "surah": 12,
    "ayahs": [
      101
    ]
  },
  "quran_dua_rabbana_atmam": {
    "type": "quran",
    "surah": 66,
    "ayahs": [
      8
    ]
  },
  "quran_dua_la_tuakhizna": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      286
    ]
  },

  "afia_body_hearing_sight": {
    "type": "dureihim",
    "filename": "82"
  },
  "afia_dua": {
    "type": "dureihim",
    "filename": "84"
  },
  "after_athan_salawat": {
    "type": "dureihim",
    "filename": "98"
  },
  "after_athan_shahada": {
    "type": "dureihim",
    "filename": "23"
  },
  "after_athan_wasilah": {
    "type": "dureihim",
    "filename": "25"
  },
  "after_food": {
    "type": "dureihim",
    "filename": "180"
  },
  "after_food_hamd_general": {
    "type": "dureihim",
    "filename": "91"
  },
  "after_milk_dua": {
    "type": "dureihim",
    "filename": "179"
  },
  "after_wudu": {
    "type": "dureihim",
    "filename": "13"
  },
  "after_wudu_tawabeen": {
    "type": "dureihim",
    "filename": "14"
  },
  "akhir_baqarah_sleep": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      285, 286
    ]
  },
  "alhamdu_atamana": {
    "type": "dureihim",
    "filename": "108"
  },
  "alhamdulillah_prayer_33": {
    "type": "dureihim",
    "filename": "69"
  },
  "alhamdulillah_sleep_33": {
    "type": "dureihim",
    "filename": "106"
  },
  "allahu_akbar_prayer_33": {
    "type": "dureihim",
    "filename": "69"
  },
  "allahu_akbar_sleep_34": {
    "type": "dureihim",
    "filename": "106"
  },
  "allahumma_aslamtu": {
    "type": "dureihim",
    "filename": "91"
  },
  "allahumma_bismika": {
    "type": "dureihim",
    "filename": "91"
  },
  "allahumma_khalaqta": {
    "type": "dureihim",
    "filename": "91"
  },
  "allahumma_qini": {
    "type": "dureihim",
    "filename": "104"
  },
  "allahumma_rabb_samawat": {
    "type": "dureihim",
    "filename": "91"
  },
  "aman_rasul_ruqyah": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      285, 286
    ]
  },
  "answered_ism_aazam": {
    "type": "dureihim",
    "filename": "65"
  },
  "answered_thul_jalal": {
    "type": "dureihim",
    "filename": "91"
  },
  "arafah_ali_dua": {
    "type": "dureihim",
    "filename": "237"
  },
  "arafah_best_dhikr": {
    "type": "dureihim",
    "filename": "237"
  },
  "arafah_prophetic_afia": {
    "type": "dureihim",
    "filename": "84"
  },
  "arafah_prophetic_huda": {
    "type": "dureihim",
    "filename": "91"
  },
  "arafah_prophetic_jame": {
    "type": "dureihim",
    "filename": "91"
  },
  "arafah_prophetic_refuge": {
    "type": "dureihim",
    "filename": "91"
  },
  "arafah_quran_hasanah": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      201
    ]
  },
  "arafah_quran_tazigh": {
    "type": "quran",
    "surah": 3,
    "ayahs": [
      8
    ]
  },
  "arafah_quran_younus": {
    "type": "quran",
    "surah": 21,
    "ayahs": [
      87
    ]
  },
  "arafah_quran_zulmna": {
    "type": "quran",
    "surah": 7,
    "ayahs": [
      23
    ]
  },
  "asbahna_morning": {
    "type": "dureihim",
    "filename": "91"
  },
  "asbahna_morning_rab_al_alamin": {
    "type": "dureihim",
    "filename": "91"
  },
  "ashhadu_himalata_arshika": {
    "type": "dureihim",
    "filename": "80"
  },
  "awudhu_kalimat": {
    "type": "dureihim",
    "filename": "216"
  },
  "awudhu_kalimat_ruqyah": {
    "type": "dureihim",
    "filename": "91"
  },
  "awudhu_qudra": {
    "type": "dureihim",
    "filename": "91"
  },
  "ayat_kursi_morning_evening": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      255
    ]
  },
  "ayat_kursi_prayer": {
    "type": "dureihim",
    "filename": "91"
  },
  "ayat_kursi_ruqyah": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      255
    ]
  },
  "ayat_kursi_sleep": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      255
    ]
  },
  "ayatan_baqarah": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      285, 286
    ]
  },
  "before_food": {
    "type": "dureihim",
    "filename": "12"
  },
  "before_wudu": {
    "type": "dureihim",
    "filename": "12"
  },
  "bika_asbahna": {
    "type": "dureihim",
    "filename": "91"
  },
  "bismika_rabbi": {
    "type": "dureihim",
    "filename": "102"
  },
  "bismillah_protection": {
    "type": "dureihim",
    "filename": "86"
  },
  "bismillah_wadatu": {
    "type": "dureihim",
    "filename": "91"
  },
  "dhikr_mashar_al_haram": {
    "type": "dureihim",
    "filename": "238"
  },
  "dhikr_missing_114": {
    "type": "dureihim",
    "filename": "114"
  },
  "dhikr_missing_115": {
    "type": "dureihim",
    "filename": "115"
  },
  "dhikr_missing_117": {
    "type": "dureihim",
    "filename": "117"
  },
  "dhikr_missing_119": {
    "type": "dureihim",
    "filename": "119"
  },
  "dhikr_missing_120": {
    "type": "dureihim",
    "filename": "120"
  },
  "dhikr_missing_123": {
    "type": "dureihim",
    "filename": "123"
  },
  "dhikr_missing_124": {
    "type": "dureihim",
    "filename": "124"
  },
  "dhikr_missing_125": {
    "type": "dureihim",
    "filename": "125"
  },
  "dhikr_missing_126": {
    "type": "dureihim",
    "filename": "126"
  },
  "dhikr_missing_127": {
    "type": "dureihim",
    "filename": "127"
  },
  "dhikr_missing_128": {
    "type": "dureihim",
    "filename": "128"
  },
  "dhikr_missing_129": {
    "type": "dureihim",
    "filename": "129"
  },
  "dhikr_missing_131": {
    "type": "dureihim",
    "filename": "131"
  },
  "dhikr_missing_132": {
    "type": "dureihim",
    "filename": "132"
  },
  "dhikr_missing_133": {
    "type": "dureihim",
    "filename": "133"
  },
  "dhikr_missing_135": {
    "type": "dureihim",
    "filename": "135"
  },
  "dhikr_missing_136": {
    "type": "dureihim",
    "filename": "136"
  },
  "dhikr_missing_139": {
    "type": "dureihim",
    "filename": "139"
  },
  "dhikr_missing_140": {
    "type": "dureihim",
    "filename": "140"
  },
  "dhikr_missing_141": {
    "type": "dureihim",
    "filename": "141"
  },
  "dhikr_missing_143": {
    "type": "dureihim",
    "filename": "143"
  },
  "dhikr_missing_144": {
    "type": "dureihim",
    "filename": "144"
  },
  "dhikr_missing_145": {
    "type": "dureihim",
    "filename": "145"
  },
  "dhikr_missing_146": {
    "type": "dureihim",
    "filename": "146"
  },
  "dhikr_missing_149": {
    "type": "dureihim",
    "filename": "149"
  },
  "dhikr_missing_150": {
    "type": "dureihim",
    "filename": "150"
  },
  "dhikr_missing_154": {
    "type": "dureihim",
    "filename": "154"
  },
  "dhikr_missing_155": {
    "type": "dureihim",
    "filename": "155"
  },
  "dhikr_missing_156": {
    "type": "dureihim",
    "filename": "156"
  },
  "dhikr_missing_157": {
    "type": "dureihim",
    "filename": "157"
  },
  "dhikr_missing_158": {
    "type": "dureihim",
    "filename": "158"
  },
  "dhikr_missing_159": {
    "type": "dureihim",
    "filename": "159"
  },
  "dhikr_missing_160": {
    "type": "dureihim",
    "filename": "160"
  },
  "dhikr_missing_161": {
    "type": "dureihim",
    "filename": "161"
  },
  "dhikr_missing_164": {
    "type": "dureihim",
    "filename": "164"
  },
  "dhikr_missing_165": {
    "type": "dureihim",
    "filename": "165"
  },
  "dhikr_missing_166": {
    "type": "dureihim",
    "filename": "166"
  },
  "dhikr_missing_169": {
    "type": "dureihim",
    "filename": "169"
  },
  "dhikr_missing_170": {
    "type": "dureihim",
    "filename": "170"
  },
  "dhikr_missing_171": {
    "type": "dureihim",
    "filename": "171"
  },
  "dhikr_missing_174": {
    "type": "dureihim",
    "filename": "174"
  },
  "dhikr_missing_177": {
    "type": "dureihim",
    "filename": "177"
  },
  "dhikr_missing_185": {
    "type": "dureihim",
    "filename": "185"
  },
  "dhikr_missing_186": {
    "type": "dureihim",
    "filename": "186"
  },
  "dhikr_missing_187": {
    "type": "dureihim",
    "filename": "187"
  },
  "dhikr_missing_19": {
    "type": "dureihim",
    "filename": "19"
  },
  "dhikr_missing_191": {
    "type": "dureihim",
    "filename": "191"
  },
  "dhikr_missing_195": {
    "type": "dureihim",
    "filename": "195"
  },
  "dhikr_missing_198": {
    "type": "dureihim",
    "filename": "198"
  },
  "dhikr_missing_199": {
    "type": "dureihim",
    "filename": "199"
  },
  "dhikr_missing_200": {
    "type": "dureihim",
    "filename": "200"
  },
  "dhikr_missing_201": {
    "type": "dureihim",
    "filename": "201"
  },
  "dhikr_missing_202": {
    "type": "dureihim",
    "filename": "202"
  },
  "dhikr_missing_203": {
    "type": "dureihim",
    "filename": "203"
  },
  "dhikr_missing_204": {
    "type": "dureihim",
    "filename": "204"
  },
  "dhikr_missing_205": {
    "type": "dureihim",
    "filename": "205"
  },
  "dhikr_missing_208": {
    "type": "dureihim",
    "filename": "208"
  },
  "dhikr_missing_214": {
    "type": "dureihim",
    "filename": "214"
  },
  "dhikr_missing_219": {
    "type": "dureihim",
    "filename": "219"
  },
  "dhikr_missing_22": {
    "type": "dureihim",
    "filename": "22"
  },
  "dhikr_missing_220": {
    "type": "dureihim",
    "filename": "220"
  },
  "dhikr_missing_222": {
    "type": "dureihim",
    "filename": "222"
  },
  "dhikr_missing_223": {
    "type": "dureihim",
    "filename": "223"
  },
  "dhikr_missing_224": {
    "type": "dureihim",
    "filename": "224"
  },
  "dhikr_missing_225": {
    "type": "dureihim",
    "filename": "225"
  },
  "dhikr_missing_24": {
    "type": "dureihim",
    "filename": "24"
  },
  "dhikr_missing_253": {
    "type": "dureihim",
    "filename": "253"
  },
  "dhikr_missing_26": {
    "type": "dureihim",
    "filename": "26"
  },
  "dhikr_missing_41": {
    "type": "dureihim",
    "filename": "41"
  },
  "dhikr_missing_45": {
    "type": "dureihim",
    "filename": "37"
  },
  "dhikr_missing_47": {
    "type": "dureihim",
    "filename": "47"
  },
  "dhikr_missing_51": {
    "type": "dureihim",
    "filename": "51"
  },
  "dhikr_missing_54": {
    "type": "dureihim",
    "filename": "54"
  },
  "dhikr_missing_66": {
    "type": "dureihim",
    "filename": "66"
  },
  "dhikr_missing_71": {
    "type": "dureihim",
    "filename": "71"
  },
  "dhikr_missing_74": {
    "type": "dureihim",
    "filename": "74"
  },
  "dhikr_missing_79": {
    "type": "dureihim",
    "filename": "79"
  },
  "dhikr_missing_85": {
    "type": "dureihim",
    "filename": "85"
  },
  "dhikr_missing_89": {
    "type": "dureihim",
    "filename": "89"
  },
  "dhikr_missing_90": {
    "type": "dureihim",
    "filename": "90"
  },
  "distress_anger_istiaadhah": {
    "type": "dureihim",
    "filename": "193"
  },
  "distress_hamm_hazan": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_hasbiyallah": {
    "type": "dureihim",
    "filename": "83"
  },
  "distress_jawami_1": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_10": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_11": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_12": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_13": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_14": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_15": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_16": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_17": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_18": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_19": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_2": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_20": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_21": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_22": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_23": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_24": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_25": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_26": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_27": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_28": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_29": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_3": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_30": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_31": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_32": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_4": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_5": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_6": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_7": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_8": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_jawami_9": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_kurb_great": {
    "type": "dureihim",
    "filename": "91"
  },
  "distress_musibah_istirja": {
    "type": "dureihim",
    "filename": "154"
  },
  "distress_yunus_dhunnoon": {
    "type": "dureihim",
    "filename": "124"
  },
  "dog_barking_night": {
    "type": "dureihim",
    "filename": "229"
  },
  "dua_between_yamani_and_black_stone": {
    "type": "dureihim",
    "filename": "235"
  },
  "eating_forget_dua": {
    "type": "dureihim",
    "filename": "226"
  },
  "enter_house_bismillah": {
    "type": "dureihim",
    "filename": "18"
  },
  "enter_masjid_dua": {
    "type": "dureihim",
    "filename": "91"
  },
  "enter_masjid_istiaadha": {
    "type": "dureihim",
    "filename": "91"
  },
  "enter_restroom": {
    "type": "dureihim",
    "filename": "10"
  },
  "enter_town": {
    "type": "dureihim",
    "filename": "91"
  },
  "falaq_morning_evening": {
    "type": "quran",
    "surah": 113,
    "ayahs": [
      1, 2, 3, 4, 5
    ]
  },
  "falaq_prayer": {
    "type": "quran",
    "surah": 113,
    "ayahs": [
      1, 2, 3, 4, 5
    ]
  },
  "falaq_ruqyah": {
    "type": "quran",
    "surah": 113,
    "ayahs": [
      1, 2, 3, 4, 5
    ]
  },
  "falaq_sleep": {
    "type": "quran",
    "surah": 113,
    "ayahs": [
      1, 2, 3, 4, 5
    ]
  },
  "fatiha_ruqyah": {
    "type": "quran",
    "surah": 1,
    "ayahs": [
      1, 2, 3, 4, 5, 6, 7
    ]
  },
  "fatirul_samawat": {
    "type": "dureihim",
    "filename": "91"
  },
  "fitra_morning": {
    "type": "dureihim",
    "filename": "91"
  },
  "food_breaking_fast_host": {
    "type": "dureihim",
    "filename": "184"
  },
  "food_guest_dua": {
    "type": "dureihim",
    "filename": "182"
  },
  "food_provider_dua": {
    "type": "dureihim",
    "filename": "183"
  },
  "go_to_masjid_noor": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_arafah": {
    "type": "dureihim",
    "filename": "237"
  },
  "great_days_ashura": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_athan_iqamah": {
    "type": "dureihim",
    "filename": "84"
  },
  "great_days_breaking_fast": {
    "type": "dureihim",
    "filename": "176"
  },
  "great_days_dhul_hijjah": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_friday": {
    "type": "dureihim",
    "filename": "98"
  },
  "great_days_friday_hour": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_la_ilaha_100": {
    "type": "dureihim",
    "filename": "93"
  },
  "great_days_night_third": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_qadr": {
    "type": "dureihim",
    "filename": "91"
  },
  "great_days_sayyid_istighfar": {
    "type": "dureihim",
    "filename": "79"
  },
  "great_days_suhoor_istighfar": {
    "type": "quran",
    "surah": 51,
    "ayahs": [
      18
    ]
  },
  "great_days_sujood_dua": {
    "type": "dureihim",
    "filename": "46"
  },
  "hajj_eid_takbeer": {
    "type": "dureihim",
    "filename": "241"
  },
  "hajj_jamarat_takbeer": {
    "type": "dureihim",
    "filename": "239"
  },
  "hajj_muzdalifah_dua": {
    "type": "dureihim",
    "filename": "238"
  },
  "hajj_safa_marwa_dua": {
    "type": "dureihim",
    "filename": "236"
  },
  "hajj_talbiyah": {
    "type": "dureihim",
    "filename": "233"
  },
  "hajj_tawaf_dua": {
    "type": "dureihim",
    "filename": "235"
  },
  "hajj_udhiyah_takbeer": {
    "type": "dureihim",
    "filename": "246"
  },
  "hasbiyallah_7": {
    "type": "dureihim",
    "filename": "83"
  },
  "hear_athan_repeat": {
    "type": "dureihim",
    "filename": "91"
  },
  "house_bismillah_shaytan": {
    "type": "dureihim",
    "filename": "12"
  },
  "house_taawwudh_night": {
    "type": "dureihim",
    "filename": "216"
  },
  "ikhlas_morning_evening": {
    "type": "quran",
    "surah": 112,
    "ayahs": [
      1, 2, 3, 4
    ]
  },
  "ikhlas_prayer": {
    "type": "quran",
    "surah": 112,
    "ayahs": [
      1, 2, 3, 4
    ]
  },
  "ikhlas_ruqyah": {
    "type": "quran",
    "surah": 112,
    "ayahs": [
      1, 2, 3, 4
    ]
  },
  "ikhlas_sleep": {
    "type": "quran",
    "surah": 112,
    "ayahs": [
      1, 2, 3, 4
    ]
  },
  "illness_pain_ruqyah": {
    "type": "dureihim",
    "filename": "91"
  },
  "illness_visit_seven_times": {
    "type": "dureihim",
    "filename": "148"
  },
  "illness_visit_tahoor": {
    "type": "dureihim",
    "filename": "147"
  },
  "istighfar_100_daily": {
    "type": "dureihim",
    "filename": "91"
  },
  "istighfar_3_prayer": {
    "type": "dureihim",
    "filename": "91"
  },
  "kafirun_ruqyah": {
    "type": "quran",
    "surah": 109,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "la_hawla_treasure_of_jannah": {
    "type": "dureihim",
    "filename": "260"
  },
  "la_ilaha_10": {
    "type": "dureihim",
    "filename": "92"
  },
  "la_ilaha_100_day": {
    "type": "dureihim",
    "filename": "93"
  },
  "la_ilaha_prayer": {
    "type": "dureihim",
    "filename": "91"
  },
  "leave_house_dua": {
    "type": "dureihim",
    "filename": "17"
  },
  "leave_house_tawakkul": {
    "type": "dureihim",
    "filename": "91"
  },
  "leave_masjid_dua": {
    "type": "dureihim",
    "filename": "21"
  },
  "leave_restroom": {
    "type": "dureihim",
    "filename": "11"
  },
  "nas_morning_evening": {
    "type": "quran",
    "surah": 114,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "nas_prayer": {
    "type": "quran",
    "surah": 114,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "nas_ruqyah": {
    "type": "quran",
    "surah": 114,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "nas_sleep": {
    "type": "quran",
    "surah": 114,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "nature_crescent": {
    "type": "dureihim",
    "filename": "91"
  },
  "nature_rain_after": {
    "type": "dureihim",
    "filename": "173"
  },
  "nature_rain_start": {
    "type": "dureihim",
    "filename": "172"
  },
  "nature_thunder": {
    "type": "dureihim",
    "filename": "168"
  },
  "nature_wind": {
    "type": "dureihim",
    "filename": "167"
  },
  "nearness_to_allah_last_third": {
    "type": "dureihim",
    "filename": "251"
  },
  "nearness_to_allah_sujood": {
    "type": "dureihim",
    "filename": "252"
  },
  "new_muslim_prayer_dua": {
    "type": "dureihim",
    "filename": "263"
  },
  "niamah_morning": {
    "type": "dureihim",
    "filename": "91"
  },
  "night_protection_children_devils": {
    "type": "dureihim",
    "filename": "267"
  },
  "occasion_arafah_ali_dua": {
    "type": "dureihim",
    "filename": "237"
  },
  "occasion_arafah_best_dhikr": {
    "type": "dureihim",
    "filename": "237"
  },
  "occasion_arafah_dua_anbiya": {
    "type": "dureihim",
    "filename": "91"
  },
  "occasion_arafah_tahlil_takbeer": {
    "type": "dureihim",
    "filename": "92"
  },
  "occasion_laylat_al_qadr": {
    "type": "dureihim",
    "filename": "91"
  },
  "occasion_laylat_al_qadr_dua_maghfirah": {
    "type": "dureihim",
    "filename": "84"
  },
  "occasion_laylat_al_qadr_tahajjud": {
    "type": "dureihim",
    "filename": "91"
  },
  "praised_person_response": {
    "type": "dureihim",
    "filename": "232"
  },
  "praising_muslim_dua": {
    "type": "dureihim",
    "filename": "231"
  },
  "prayer_aanni_ala_dhikrika": {
    "type": "dureihim",
    "filename": "59"
  },
  "prayer_ajirni_min_nar_7": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_before_tasleem_1": {
    "type": "dureihim",
    "filename": "55"
  },
  "prayer_before_tasleem_10": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_before_tasleem_11": {
    "type": "dureihim",
    "filename": "65"
  },
  "prayer_before_tasleem_2": {
    "type": "dureihim",
    "filename": "57"
  },
  "prayer_before_tasleem_3": {
    "type": "dureihim",
    "filename": "56"
  },
  "prayer_before_tasleem_4": {
    "type": "dureihim",
    "filename": "58"
  },
  "prayer_before_tasleem_5": {
    "type": "dureihim",
    "filename": "59"
  },
  "prayer_before_tasleem_6": {
    "type": "dureihim",
    "filename": "60"
  },
  "prayer_before_tasleem_7": {
    "type": "dureihim",
    "filename": "61"
  },
  "prayer_before_tasleem_8": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_before_tasleem_9": {
    "type": "dureihim",
    "filename": "63"
  },
  "prayer_between_sujud": {
    "type": "dureihim",
    "filename": "48"
  },
  "prayer_between_sujud_2": {
    "type": "dureihim",
    "filename": "49"
  },
  "prayer_ilm_nafi": {
    "type": "dureihim",
    "filename": "95"
  },
  "prayer_istiaadha_bukhari": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_istiftah_1": {
    "type": "dureihim",
    "filename": "27"
  },
  "prayer_istiftah_2": {
    "type": "dureihim",
    "filename": "28"
  },
  "prayer_istiftah_3": {
    "type": "dureihim",
    "filename": "29"
  },
  "prayer_istiftah_4": {
    "type": "dureihim",
    "filename": "30"
  },
  "prayer_istiftah_5": {
    "type": "dureihim",
    "filename": "31"
  },
  "prayer_istiftah_6": {
    "type": "dureihim",
    "filename": "32"
  },
  "prayer_istighfar_khataaya": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_la_ilaha_yuhyi_10": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_qini_v1": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_qunut_1": {
    "type": "dureihim",
    "filename": "116"
  },
  "prayer_qunut_2": {
    "type": "dureihim",
    "filename": "47"
  },
  "prayer_qunut_3": {
    "type": "dureihim",
    "filename": "118"
  },
  "prayer_raf_ruku_1": {
    "type": "dureihim",
    "filename": "38"
  },
  "prayer_raf_ruku_2": {
    "type": "dureihim",
    "filename": "39"
  },
  "prayer_raf_ruku_3": {
    "type": "dureihim",
    "filename": "40"
  },
  "prayer_ruku_1": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_ruku_2": {
    "type": "dureihim",
    "filename": "35"
  },
  "prayer_ruku_3": {
    "type": "dureihim",
    "filename": "34"
  },
  "prayer_ruku_4": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_ruku_5": {
    "type": "dureihim",
    "filename": "37"
  },
  "prayer_sujud_1": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_sujud_2": {
    "type": "dureihim",
    "filename": "46"
  },
  "prayer_sujud_3": {
    "type": "dureihim",
    "filename": "44"
  },
  "prayer_sujud_4": {
    "type": "dureihim",
    "filename": "34"
  },
  "prayer_sujud_5": {
    "type": "dureihim",
    "filename": "35"
  },
  "prayer_sujud_6": {
    "type": "dureihim",
    "filename": "37"
  },
  "prayer_sujud_7": {
    "type": "dureihim",
    "filename": "47"
  },
  "prayer_sujud_tilawah": {
    "type": "dureihim",
    "filename": "50"
  },
  "prayer_sujud_tilawah_2": {
    "type": "dureihim",
    "filename": "51"
  },
  "prayer_tasbih_10_alternate": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_tasbih_25_alternate": {
    "type": "dureihim",
    "filename": "92"
  },
  "prayer_tasbih_34_alternate": {
    "type": "dureihim",
    "filename": "91"
  },
  "prayer_tashahhud_text": {
    "type": "dureihim",
    "filename": "52"
  },
  "prophet_tasbih_by_right_hand": {
    "type": "dureihim",
    "filename": "266"
  },
  "protection_against_rebel_devils": {
    "type": "dureihim",
    "filename": "247"
  },
  "protection_anxiety_grief": {
    "type": "dureihim",
    "filename": "121"
  },
  "protection_body_injury": {
    "type": "dureihim",
    "filename": "91"
  },
  "protection_children_family": {
    "type": "dureihim",
    "filename": "91"
  },
  "protection_dhikr_waswas": {
    "type": "dureihim",
    "filename": "134"
  },
  "protection_entire_creation": {
    "type": "dureihim",
    "filename": "91"
  },
  "protection_entry_exit_plague": {
    "type": "dureihim",
    "filename": "91"
  },
  "protection_envy_evil_eye": {
    "type": "dureihim",
    "filename": "91"
  },
  "protection_envy_seeing_admired_thing": {
    "type": "dureihim",
    "filename": "244"
  },
  "protection_sleep_fears": {
    "type": "dureihim",
    "filename": "91"
  },
  "quran_dua_forgiveness": {
    "type": "quran",
    "surah": 59,
    "ayahs": [
      10
    ]
  },
  "quran_dua_hasanah": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      201
    ]
  },
  "quran_dua_mercy": {
    "type": "quran",
    "surah": 18,
    "ayahs": [
      10
    ]
  },
  "quran_dua_parent": {
    "type": "quran",
    "surah": 14,
    "ayahs": [
      40, 41
    ]
  },
  "quran_dua_sharih": {
    "type": "quran",
    "surah": 20,
    "ayahs": [
      25, 26, 27, 28
    ]
  },
  "quran_dua_solitude": {
    "type": "quran",
    "surah": 21,
    "ayahs": [
      89
    ]
  },
  "quran_dua_spouse": {
    "type": "quran",
    "surah": 25,
    "ayahs": [
      74
    ]
  },
  "quran_dua_tazigh": {
    "type": "quran",
    "surah": 3,
    "ayahs": [
      8
    ]
  },
  "quran_dua_younus": {
    "type": "quran",
    "surah": 21,
    "ayahs": [
      87
    ]
  },
  "quran_dua_zulmna": {
    "type": "quran",
    "surah": 7,
    "ayahs": [
      23
    ]
  },
  "rabb_nas": {
    "type": "dureihim",
    "filename": "91"
  },
  "raditu": {
    "type": "dureihim",
    "filename": "87"
  },
  "repentance_seeking_forgiveness_100": {
    "type": "dureihim",
    "filename": "249"
  },
  "reply_non_muslim_salaam": {
    "type": "dureihim",
    "filename": "227"
  },
  "resident_to_traveler": {
    "type": "dureihim",
    "filename": "212"
  },
  "rooster_donkey_sound_dua": {
    "type": "dureihim",
    "filename": "228"
  },
  "ruqyah_ain_qalam": {
    "type": "quran",
    "surah": 68,
    "ayahs": [
      51, 52
    ]
  },
  "ruqyah_baqarah_intro": {
    "type": "quran",
    "surah": 2,
    "ayahs": [
      1, 2, 3, 4, 5
    ]
  },
  "ruqyah_bismillah_protection": {
    "type": "dureihim",
    "filename": "86"
  },
  "ruqyah_bismillah_turbat_ardina": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_faza_shayatin": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_jibril": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_jibril_alternate": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_jibril_self": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_khalaq": {
    "type": "dureihim",
    "filename": "216"
  },
  "ruqyah_khambash": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_muawwidhat_blow": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_rubb_nas_bidal_shifa": {
    "type": "dureihim",
    "filename": "91"
  },
  "ruqyah_sihr_arafah": {
    "type": "quran",
    "surah": 7,
    "ayahs": [
      117, 118, 119, 120, 121, 122
    ]
  },
  "ruqyah_sihr_taha": {
    "type": "quran",
    "surah": 20,
    "ayahs": [
      69
    ]
  },
  "ruqyah_sihr_yunus": {
    "type": "quran",
    "surah": 10,
    "ayahs": [
      81, 82
    ]
  },
  "ruqyah_yabrik": {
    "type": "dureihim",
    "filename": "91"
  },
  "salawat_100": {
    "type": "dureihim",
    "filename": "98"
  },
  "salawat_100_prayer": {
    "type": "dureihim",
    "filename": "98"
  },
  "salawat_ibrahimiya": {
    "type": "dureihim",
    "filename": "53"
  },
  "salawat_ibrahimiya_prayer": {
    "type": "dureihim",
    "filename": "53"
  },
  "sayyid_istighfar": {
    "type": "dureihim",
    "filename": "79"
  },
  "sleep_ali_imran_waking": {
    "type": "dureihim",
    "filename": "91"
  },
  "sleep_bad_dream": {
    "type": "dureihim",
    "filename": "91"
  },
  "sleep_faza": {
    "type": "dureihim",
    "filename": "245"
  },
  "sleep_faza_istiaadha": {
    "type": "dureihim",
    "filename": "113"
  },
  "sleep_insomnia_dua": {
    "type": "dureihim",
    "filename": "91"
  },
  "sleep_kafirun_recitation": {
    "type": "quran",
    "surah": 109,
    "ayahs": [
      1, 2, 3, 4, 5, 6
    ]
  },
  "sleep_mulk_sajdah": {
    "type": "dureihim",
    "filename": "91"
  },
  "sleep_taqallub": {
    "type": "dureihim",
    "filename": "91"
  },
  "sleep_waking_up_1": {
    "type": "dureihim",
    "filename": "1"
  },
  "sleep_waking_up_2": {
    "type": "dureihim",
    "filename": "3"
  },
  "sneeze_tashmeet_dua": {
    "type": "dureihim",
    "filename": "188"
  },
  "social_afflicted": {
    "type": "dureihim",
    "filename": "194"
  },
  "social_anger": {
    "type": "dureihim",
    "filename": "193"
  },
  "social_condolence": {
    "type": "dureihim",
    "filename": "91"
  },
  "social_market": {
    "type": "dureihim",
    "filename": "209"
  },
  "social_married": {
    "type": "dureihim",
    "filename": "190"
  },
  "social_sick_visit_1": {
    "type": "dureihim",
    "filename": "147"
  },
  "social_sick_visit_2": {
    "type": "dureihim",
    "filename": "148"
  },
  "social_sneezing": {
    "type": "dureihim",
    "filename": "91"
  },
  "social_wear_new_clothes_1": {
    "type": "dureihim",
    "filename": "7"
  },
  "social_wear_new_clothes_2": {
    "type": "dureihim",
    "filename": "91"
  },
  "subhan_allah_100": {
    "type": "dureihim",
    "filename": "91"
  },
  "subhan_allah_adada_khalqihi": {
    "type": "dureihim",
    "filename": "94"
  },
  "subhan_allah_prayer_33": {
    "type": "dureihim",
    "filename": "69"
  },
  "subhan_allah_sleep_33": {
    "type": "dureihim",
    "filename": "106"
  },
  "sujud_shukr_action": {
    "type": "dureihim",
    "filename": "242"
  },
  "sunnah_bed_shake": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_covering_vessels": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_greeting_children": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_istikhara_dua": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_lick_fingers": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_salat_nafilah_house": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_sit_drink": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_sleep_wudu": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_smile": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_sujood_shukr": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_tahajjud_siwak": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_tahiyyat_masjid": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_travel_tasbih_takbeer": {
    "type": "dureihim",
    "filename": "91"
  },
  "sunnah_wudu_prayer": {
    "type": "dureihim",
    "filename": "91"
  },
  "supplication_for_whom_you_insulted": {
    "type": "dureihim",
    "filename": "230"
  },
  "tahlil_prayer": {
    "type": "dureihim",
    "filename": "68"
  },
  "takbeer_black_stone": {
    "type": "dureihim",
    "filename": "234"
  },
  "takbeer_throwing_pebbles": {
    "type": "dureihim",
    "filename": "239"
  },
  "take_off_clothes": {
    "type": "dureihim",
    "filename": "12"
  },
  "talbiyah_hajj_umrah": {
    "type": "dureihim",
    "filename": "233"
  },
  "tamam_miah_prayer": {
    "type": "dureihim",
    "filename": "69"
  },
  "tasbih_gaining_thousand_good_deeds": {
    "type": "dureihim",
    "filename": "258"
  },
  "travel_mount_fail": {
    "type": "dureihim",
    "filename": "12"
  },
  "travel_return": {
    "type": "dureihim",
    "filename": "91"
  },
  "travel_sahar": {
    "type": "dureihim",
    "filename": "215"
  },
  "travel_start": {
    "type": "dureihim",
    "filename": "207"
  },
  "travel_takbeer_tasbih": {
    "type": "dureihim",
    "filename": "91"
  },
  "travel_tewdeea_resident": {
    "type": "dureihim",
    "filename": "213"
  },
  "traveler_to_resident": {
    "type": "dureihim",
    "filename": "211"
  },
  "vehicle_mount_dua": {
    "type": "dureihim",
    "filename": "91"
  },
  "wear_clothes": {
    "type": "dureihim",
    "filename": "6"
  },
  "wear_clothes_general": {
    "type": "dureihim",
    "filename": "5"
  },
  "ya_hayyu": {
    "type": "dureihim",
    "filename": "88"
  }
};
